betagouv/recommandations-collaboratives

frontend_tests/cypress/e2e/project/navigation/canAccessAdministration.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canChangeProjectInformation.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canChangeProjectLocation.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canInviteAMember.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canInviteASwitchtender.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canResendAMemberInvitation.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canResendASwitchtenderInvitation.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canRevokeAMemberInvitation.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canRevokeASwitchtenderInvitation.cy.js, frontend_tests/cypress/e2e/project/switchtender/assigned/administration/canResendAMemberInvitation.cy.js, frontend_tests/cypress/e2e/project/switchtender/assigned/administration/canRevokeAMemberInvitation.cy.js, urbanvitaliz/apps/projects/templates/projects/project/navigation.html
Carte trello https://trello.com/c/FeXVVxOW/1717-wording-changer-le-nom-de-longlet-administration-en-param%C3%A8tres
=> [Project] Administration tab changed to `Paramètres` tab

urbanvitaliz/frontend/src/css/crm.css
Ceci est un hotfix pour résoudre un problème de layout qui mérite un fix de fond concernant le design de la barre d'entête de la vue CRM
Je propose de créer une carte Trello pour traiter le problème de design/inté concernant la fonction de cet entête afin de permettre à l'utilisateur de voir le contexte malgré le scroll Jusqu'ici, ceci était implémenté grace à l'utilisation de la règle CSS `position: sticky`. Or cette règle est fragile lorsque l'élément ainsi positionné a du contenu de taille variable, car cette variation, lorsqu'elle grandit, couvre des éléments dans le flow css qui suit.
=> [crm] Fix padding CRM main

urbanvitaliz/frontend/src/css/geocoderBAN.css, urbanvitaliz/frontend/src/js/apps/projectLocation.js, urbanvitaliz/frontend/src/js/apps/projectLocationEdit.js, urbanvitaliz/frontend/src/js/components/ProjectLocation.js, urbanvitaliz/frontend/src/js/components/ProjectLocationEdit.js
Ce commit est un effort pour essayer de resoudre un problème qui apparait uniquement sur l'environnement `staging`.
Le bug n'apparait pas du tout en local, et il est donc impossible de le tester sans déployer. 
J'ai essayé d'utiliser `vite preview` afin d'esssayer de réproduire le problème en local, mais la commande ne rend pas correctement avec la configuration actuelle du projet.
Ce commit tente 2 choses:
- Changer l'endroit de chargement de la librairie `leaflet.css` en dehors des composants qui l'utilisent pour le faire dans les fichiers JS qui appellent ces composants, et faire en sorte que les fichiers CSS qui surchargent les styles soient chargés après `leaflet.css`
- En dernier recours, ajouter `!important` aux régles qui se font écraser en staging
----
Ci dessous le problème, et …
=> [geoloc] Attempt to fix loading order of leaflet styles

urbanvitaliz/apps/onboarding/tests.py, urbanvitaliz/apps/onboarding/views.py, urbanvitaliz/apps/projects/templates/projects/project/location.html, urbanvitaliz/apps/projects/tests/test_projects.py, urbanvitaliz/apps/projects/views/detail.py
Le formulaire de mise à jour de la géoloc est désormais proposé avant l'état des lieux.
Voici les nouveaux scénarios :
1) Utilisateur connecté : onboarding > location > survey
2) Utilisateur existant non connecté (reconnu par le mail) : onboarding > auth > onboarding > location > survey
3) Utilisateur non connu : onboarding > set-password > location > survey
=> Ajout de l'écran de mise à jour de la géoloc affinée après le formulaire de saisine

urbanvitaliz/apps/crm/tests/test_topics.py, urbanvitaliz/apps/crm/views.py, urbanvitaliz/apps/projects/tests/test_rest.py, urbanvitaliz/apps/projects/views/rest.py
Les thématiques associées à une recommandation supprimée ou à un projet supprimé remontaient quand même.
Un filtre sur les objets associés à la thématique pour vérifier qui n'ont pas de date de suppression.
J'ai également supprimé le filtre sur le site en cours car le `CurrentSiteManager` s'en charge déjà (ce qui produisait dans la requête un  ("projects_topic"."site_id" = 2 AND "projects_topic"."site_id" = 2) )
=> Enlève les thématiques non utilisées de l'API, du nuage et de l'export CSV

urbanvitaliz/apps/crm/forms.py, urbanvitaliz/apps/crm/templates/crm/user_update.html, urbanvitaliz/apps/crm/tests/test_user.py, urbanvitaliz/apps/crm/views.py
La modification des informations d'un utilisateur était possible depuis le CRM, mais le champs mail était grisé.
Contraintes :
- l'email est aussi le `username`
- il y a une validation des adresses mails
- il ne faut pas qu'on puisse créer des doublons d'adresses mail.
=> [CRM] Possibilité de modifier l'email d'un utilisateur

urbanvitaliz/apps/crm/templates/crm/user_details.html
[Trello Ticket](https://trello.com/c/T3X8l4kE/1875-crm-le-bouton-g%C3%A9rer-lutilisateur-ne-saffiche-pas-bien-selon-la-taille-ou-zoom-d%C3%A9cran)
Comme vu ensemble petite amélioration avant de reprendre le fonctionnement des challenges :
=> [fix] Add custom badge for challenge groups in user details page

recoco/settings/common.py
When editing :
Before fix : 
After fix : 
The markdown module has [an extension "sane list"](https://python-markdown.github.io/extensions/sane_lists/) to fix this behavior, and markdownx allows to enable it with setting  `MARKDOWNX_MARKDOWN_EXTENSIONS`.
=> fix: an ordered list followed by a bullet list results in a large ordered list

recoco/apps/crm/templates/crm/user_update.html
User thinks redirect after form success is not working. But actually, it's because the error messages are not displayed.
After :
=> fix: show pretty error messages in a user's update form

recoco/apps/addressbook/tests.py, recoco/apps/addressbook/views.py
In the address book section, it is possible to add a new organization.
The organization suggestion only searches the current site, and if you submitted anyway, a duplicate organization will be created, even if the organization of the same name already exists on another site.
This behavior creates duplicate organization and errors during project creation (/onboarding/prefill).
Solution :
Just use Organization.get_or_create() instead Organization.on_site.get_or_create().
=> fix: use same get_or_create to avoid duplicate organization

recoco/apps/projects/forms.py, recoco/apps/projects/models.py, recoco/apps/projects/templates/projects/project/administration_panel.html, recoco/apps/projects/tests/test_administration.py, recoco/apps/projects/views/administration.py, recoco/templates/default_site/actstream/action.html, recoco/verbs.py
Advisors can now edit project information
And actions are tracked : 
Warning : remember to update permissions after deployment (`python manage.py update_permissions`)
=> [feat] Advisor can edit project fields on parameters tab

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss
Il s'agit de :
Ajout d'une règle CSS permettant d'écraser le style sousligné par défaut
=> [hotfix] override link style

recoco/apps/onboarding/views.py
Il s'agit de :
Le template de mail d'invitation sur un projet a besoin du prénom et du nom.
=> https://trello.com/c/Ee9NM9Td
=> fix: Ajout des paramètres manquant à l'invitation lors de la création d'un projet par un conseiller

notebooks/materialized_views.ipynb, recoco/apps/metrics/apps.py, recoco/apps/metrics/management/commands/update_materialized_views.py, recoco/apps/metrics/processor.py, recoco/apps/metrics/tests/sql_queries/view_test_django_qs.py, recoco/apps/metrics/tests/sql_queries/view_test_raw_sql.sql, recoco/apps/metrics/tests/sql_queries/view_test_simple.sql, recoco/apps/metrics/tests/test_processor.py, recoco/settings/common.py, recoco/settings/development.py.example
Il s'agit de :
Ajout d'une nouvelle app django contenant des outils pour créer des vues matérialisées.
- pour pouvoir fournir une commande pour re-créer et refresh les vues matérialisées
```python manage.py update_materialized_view```
- on peut eventuellement créer des models correspondant aux vues, en mode `managed = False`, ainsi que des pages d'admin
A challenger ! :-)
- Il faut créer un fichier dans `apps/metrics/sql_queries` qui contient la requête sql qui permet de créer la vue
- Ce fichier peut être du sql brut, ou bien un module python qui possède une méthode `get_queryset` qui retourne un queryset django
- Il faut ensuite référencer la vue dans les settings (`MATERIALIZED_VIEWS_DEF`), en précisant les index souhaités
- Il faut enfin lancer la commande `update_materialized_view`
=> feat: metrics and materialized views

recoco/apps/projects/utils.py, recoco/templates/default_site/header/menu-top-secondary.html
Il s'agit de :
Dans le header > dropdown des projets l'affichage a été modifié pour que le du nom de la commune apparaisse en premier et que ce ne soit plus l'adresse du projet qui apparaisse.
close #417
=> Fix/adress project dropdown#417

recoco/apps/home/rest.py, recoco/apps/home/tests/test_rest.py, recoco/rest_api/urls.py, recoco/urls.py
Il s'agit de :
Ajout d'un endpoint d'API pour marquer toutes les notifications d'un utilisateur comme lues depuis le front.
resolves #423 
cc @Jeremy-Bojko
=> feat: add api endpoint to mark all notifications as read for a user

recoco/apps/metrics/management/commands/update_materialized_views.py, recoco/apps/metrics/processor.py, recoco/apps/metrics/tests/test_processor.py
Il s'agit de :
Le fait de supprimer les vues matérialisées et les recréer entraine des problèmes au niveau de l'attribution des droits sur les schemas.
Désormais, on ne fait que du refresh et j'ai passé tous les requêtes de création (schema, vues, index) en `IF NOT EXISTS`.
=> fix: do not drop materialized view anymore

recoco/templates/default_site/header/menu-top-secondary.html, recoco/templates/default_site/header/menu-top.html
Il s'agit de :
Cette PR est liée à [celle de multisite](https://github.com/betagouv/recoco-portails/pull/76).
Modification de menu secondaire pour l'ajouter au premier header de manière à n'avoir qu'une ligne de header.
La modification touche au fichier générateur des pf.
Au cas où cette modification créerait trop de changement pour les utilisateurs finaux, le code précédant a été gardé sous forme de commentaire.
[Lien du ticket github project associé](https://github.com/betagouv/recommandations-collaboratives/issues/421)
Au cas où les modifications cassent quelque chose en prod, je pense qu'il serait plus prudent d'ajouter cette PR et celle associée à la prochaine phase de test en preprod.
=> [multisite] fix - merge secondary menu with the first one for pf

recoco/templates/default_site/account/email/email_confirmation_signup_message.html, recoco/templates/default_site/account/email/email_confirmation_subject.txt, recoco/templates/default_site/account/email/password_reset_key_message.html, recoco/templates/default_site/account/email/password_reset_key_subject.txt, recoco/templates/default_site/account/password_reset_from_key.html, recoco/templates/default_site/magicauth/email.html, recoco/templates/default_site/magicauth/email.txt
Il s'agit de :
Modification des fichiers emails et passwords pour les dossiers account et magicauth pour changer les références à UrbanVitaliz par une référence générique. Ceci permettant aux futures plateformes de bénéficier des fichiers par défauts pour les mails et les modifications de mots de passe.
Cette PR est liée à [celle-ci](https://github.com/betagouv/recoco-portails/pull/80) car elle permettra de bien envoyer des mails générique et non avec des occurances persistantes d'UV.
Pour être sûr que cela fonctionne, faire des tests des emails.
=> [siteDefault] fix - change UV terms by generic ones for site by default

recoco/apps/projects/templates/projects/project/list-kanban.html
Il s'agit de :
Sur certaines version de Firefox, il était impossible de drag and drop les projets du kanban.
=> [hotfix] dragndrop firefox

recoco/apps/projects/serializers.py, recoco/apps/projects/tests/test_rest.py, recoco/apps/projects/views/rest.py, recoco/apps/survey/serializers.py, recoco/apps/survey/tests/test_rest.py, recoco/apps/survey/views/rest.py, recoco/rest_api/urls.py, recoco/settings/common.py
Il s'agit de :
Modification et extension de l'API REST actuelle, pour préparer https://github.com/betagouv/recommandations-collaboratives/pull/391
Le but étant d'utiliser les même serializers pour les payload du webhook et l'API.
- modification des serializers des projets pour extraire les données qui concerne le user dans un contexte de requête http
- ajout d'un endpoint API pour obtenir les sessions
- ajout d'un endpoint API pour obtenir les answers
=> feat: extend the rest API

recoco/templates/default_site/header/dropdown-menu-notifications.html, recoco/templates/default_site/user/user_card.html
Il s'agit de :
Dans la page projet, le tooltip d'un user s'ouvre correctement au click : 
Close #503
=> [fix] tooltip info user on gravatar click

recoco/templates/default_site/header/menu-top-user-tools.html
Il s'agit de :
Changement des liens de la documentation admin de portail et conseiller d'un projet dans le menu déroulant au clique sur son compte.
Changement du type de lien pour s'ouvrir vers un nouvel onglet.
[Lien ticket github project](https://github.com/betagouv/recommandations-collaboratives/issues/495)
=> [fix] change account dropdown menu documentation links 

recoco/apps/projects/templates/projects/project/list-kanban.html
Il s'agit de :
Modification du titre de la page du kanban.
Avant : 
Après :
=> [fix] update kanban page title

recoco/apps/survey/static/survey/css/widget/qs_summary_card.scss, recoco/apps/survey/templates/survey/widgets/qs_summary_card.html
Il s'agit de :
Ajout d'une largeur sur la div contenant les commentaires de réponses à létat des lieux pour éviter les dépassements de texte. 
Avant : 
Après : 
Close #372
=> [fix] change width div for summary card to avoid text overflow #372

recoco/apps/crm/templates/crm/fragments/sidebar.html
Il s'agit de :
Modification de la variable crm_user.projects_switchtended_on_site.all à crm_user.projects_switchtended_per_site.all pour afficher la liste des projets conseillés par l'utilisateur donné.
Avant : 
Après :
=> [fix] update var to show the project advise list correctly

frontend_tests/README.md, frontend_tests/package.json
Il s'agit de :
Mise à jour de la documentation pour les tests frontend. 
Finalement, le fichier de paramétrage `frontend_tests` reste nécessaire notamment pour lancer la commande `update_permissions`
Le script dans le package.json a donc été mis à jour ainsi que la documentation.
=> [fix] readme and script in package.json

recoco/apps/projects/views/__init__.py
Il s'agit de :
Dans la page modération : 
- Lorsque l'on click sur `Accepter et rejoindre`, l'utilisateur rejoint en tant que __conseiller__
Resolve #628
=> [fix] accept and become advisor in moderation page

recoco/templates/default_site/header/menu-top-logo.html
Il s'agit de :
Si déconnecté : le header d'un portail n'affiche plus le nom du portail à côté du logo s'il est disponible
=> [fix] duplicating portal name even if the logo is available

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/apps/home/static/home/css/statistics/statistics.scss, recoco/apps/home/templates/home/statistics.html
Il s'agit de :
- Réglage de la hauteur de la map
- Réglage de la hauteur du graphique
- Correction d'une type
=> [fix] typo + map height in statistics page

recoco/apps/projects/static/projects/css/kanban.scss, recoco/apps/projects/templates/projects/project/list-kanban.html
Il s'agit de :
Le nom des projets reste maintenant sur 1 seul ligne,mais est correctement coupé.
Resolve #614
=> [fix] kanban overflow + BEM css style

recoco/apps/projects/static/projects/css/kanban.scss, recoco/apps/projects/templates/projects/project/list-kanban.html, recoco/frontend/src/js/store/projects.js
Il s'agit de :
- Résolution du bug qui affichait à tort tous les projets de EQ publié à partir d'une autre portail.
Resolve #686 
- Ajout de la mention  "Envoyé sur" sur le portail A lorqu'un projet est publié vers un autre portail  
Resolve #629
=> [fix] kanban staff falsy publish mention

recoco/apps/projects/templates/projects/project/fragments/survey_grid.html
=> Lors du partage de l'EDL, ne pas afficher les CTA de complétion et de partage 

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/apps/projects/static/projects/css/fragments/project_banner/project_banner.scss, recoco/apps/projects/templates/projects/project/actions.html, recoco/apps/projects/templates/projects/project/fragments/project_banner/join_project_banner.html, recoco/apps/projects/templates/projects/project/knowledge.html, recoco/apps/projects/templates/projects/project/navigation.html, recoco/apps/projects/templates/projects/project/overview.html, recoco/frontend/src/js/store/showRole.js, recoco/frontend/vite.config.js
Il s'agit de :
Changement de la couleur de la bannière lorsque l'on est pas observateur.trice ou conseiller.e d'un projet.
Ajout de lien pour devenir observateur.trice ou conseiller.e
Ouverture de la fenêtre modale de sélection de rôle une fois un rôle choisi avec les boutons indiqués au dessus.
Suppression de la transparence sur le contenu.
Close #748
=> [fix] update banner when not observer nor advisor

recoco/apps/projects/static/projects/css/kanban.scss, recoco/apps/projects/templates/projects/project/fragments/list-toolbars.html, recoco/apps/projects/templates/projects/project/fragments/personal_dashboard/personal_dashboard_header.html, recoco/apps/projects/templates/projects/project/fragments/region_filter.html, recoco/apps/projects/templates/projects/project/list-kanban.html
Il s'agit de :
Ajout du responsive pour les petits écrans 
**Écrans larges :**
---
**Écrans moins large :**
=> [style] Affichage de l'entête du tableau de bord sur petit écrans

pyproject.toml, recoco/settings/frontend_tests.py.example, recoco/settings/frontend_tests_permissions.py.example
Il s'agit de :
Désactivation des rules ruff F403 et F405 dans les modules python de settings.
Compte-tenu de l'utilisation en mode "surcharge", ces règles ne sont pas pertinentes et n'apportent pas de quelité de code supplémentaire sur cette partie du code.
=> [fix] Disable some ruff rules in settings modules

recoco/templates/default_site/tools/editor.html
Il s'agit de :
Changement de l'affichage du bouton enregistrer pour modifier un commentaire sur une ressource.
Il affiche maintenant "Enregistrer en brouillon" pour les ressources en brouillon :
Resolved #797
=> [fix] change save button display for drafted task #797

recoco/apps/pages/templates/pages/showcase_page.html
Il s'agit de :
Modification du rendu de la page cas d'usage pour ne plus afficher le cadre de la section citation si cette dernière n'est pas remplie.
Avant : 
Après :
=> [fix] hide citation section if it's content is empty

recoco/apps/metrics/tests/test_command.py
Il s'agit de :
Pour l'activer, ajouter cette ligne dans `development.py`, juste avant `load_dotenv`:
```python
os.environ.setdefault("SKIP_TEST_METRICS_CREATE_ROLES", "true")
load_dotenv()
...
```
=> [fix] Add a trick to skip metrics tests that create roles

recoco/apps/home/static/home/css/home/home.scss
Il s'agit de :
Modification du bleu de la classe "custom-banner" pour la mettre à la teinte du dsfr.
Exemple de la classe :
=> [fix] add dsfr blue to custom banner

recoco/frontend/src/js/store/previewModal.js
Il s'agit de :
Un problème survenait lors du clic sur une notif ou lors d'un partage d'url type https://urbanvitaliz.fr/project/2345/actions#action-5137
=> [fix] Ouverture de la modal de reco si son id est passé dans l'url

recoco/apps/projects/views/administration.py, recoco/apps/projects/views/detail.py
Il s'agit de :
La méthode `is_regional_actor_for_project` fait appel à project.commune.department. Un prefetch permet d'éviter des requêtes supplémentaires.
=> [chore] Ajout de prefetch manquants

recoco/apps/home/static/home/css/home/home.scss, recoco/apps/home/templates/home/accessibility.html
Il s'agit de :
Modification de la page de déclaration d'accessibilité et de l'affichage des liens contenus dans des balises li pour qu'ils s'affichent comme un lien "normal".
Resolve [#977](https://github.com/betagouv/recommandations-collaboratives/issues/977)
=> [feat] update accessibility page and correct link in li style

recoco/frontend/src/js/components/MenuNotifications.js, recoco/templates/default_site/header/dropdown-menu-notifications.html
Il s'agit de :
Il est maintenant possible d'ouvrir les notifications à l'aide d'un : 
- `Ctr+click`
- `Cmd+click` 
- menu contextuel
pour l'ouvrir dans un nouvel onglet.
Resolve #995
=> [feat] Ouverture des notification dans un nouvel onglet possible

recoco/apps/crm/views.py, recoco/apps/home/management/commands/update_permissions.py, recoco/apps/projects/models.py, recoco/apps/projects/utils.py, recoco/apps/projects/views/__init__.py, recoco/apps/projects/views/rest.py
…want to administrate their project from another site
Il s'agit de :
=> Permettre à un porteur de projet de gérér son projet depuis une autre plateforme en cas de multipublication

recoco/apps/addressbook/serializers.py, recoco/apps/webhook/signals.py, recoco/apps/webhook/tests/test_signals.py
Il s'agit de :
J'avais désactivé les champs `_link` des payloads de l'API, à cause d'une erreur sur la partie webhook, qui utilise les serializers DRF, mais sans contexte.
J'ai fait ce fix pour les réactiver, en ajoutant un test coté webhook.
=> [fix] Issue with use of DRF serializers in webhook

recoco/apps/addressbook/apps.py, recoco/apps/addressbook/rest.py, recoco/apps/addressbook/tests/test_rest_contact.py
Il s'agit de :
- filtre sur le nom de l'organisation, type "startswith": `/api/addressbook/contacts/?orga-startswith=B`
- l'email du contact est désormais pris en compte dans la recherche
=> [feat] Contact API : filtrer sur les noms d'organisation et recherche par email

recoco/apps/survey/models.py, recoco/apps/survey/tests/test_edit.py, recoco/apps/survey/tests/test_models.py
Il s'agit de :
Pour vérifier l'unicité, le champ slug s'appuyait sur le manager par défaut, qui exclue les questions marquées comme `deleted`. Désormais, il prend en compte toutes les questions existantes.
=> [fix] Bug sur le slug du model Question

recoco/apps/crm/views.py, recoco/apps/reminders/api.py, recoco/apps/reminders/tests.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/983
=> [fix] Mail de rappel sur projet en pause

recoco/apps/crm/templates/crm/organization_list.html, recoco/apps/crm/templates/crm/project_list.html, recoco/apps/crm/templates/crm/user_list.html, recoco/apps/projects/templates/projects/project/documents.html, recoco/apps/projects/templates/projects/project/list-map.html, recoco/apps/resources/templates/resources/resource/list.html, recoco/apps/survey/templates/survey/editor/survey/details.html
Il s'agit de :
Aux endroit où on utilise le templatetag `pluralize`, on fait souvent 2 requêtes de type `count` inutilement.
=> [fix] N+1 pluralize

recoco/settings/common.py
Il s'agit de :
Doc: https://github.com/etianen/django-watson/wiki/language-support
A faire après avoir mergé:
```bash
./manage.py migrate watson zero
./manage.py migrate watson
./manage.py buildwatson
```
=> [fix] Ajout de la config french pour watson

recoco/apps/invites/tests.py, recoco/apps/invites/views.py, recoco/apps/projects/tests/test_project_inactive.py, recoco/apps/social_account/adapters.py, recoco/apps/social_account/provider.py
Il s'agit de :
Le champ `email` n'étant pas unique pour un `User`, on doit faire un get en prenant le champ `username`, qui doit contenir l'email.
Ca doit fixer [ce bug sentry](https://sentry.incubateur.net/organizations/betagouv/issues/160028/?environment=production&project=178&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=1)
=> [fix] Mistake with username vs email

recoco/apps/projects/tests/test_projects.py, recoco/apps/projects/views/__init__.py
Il s'agit de :
Changement de l'url par défaut lorsque l'on veut accéder à tous les projets pour que les conseiller.es arrivent sur la vue kanban au lieu de la vue liste.
Pour info, je n'ai pas changer le nom des urls, mais ça fait un peu bizarre de rediriger les advisor vers l'url staff.
Resolve #1128
=> Changement de l'url par défaut de la page de prévisualisation des projets pour les conseiller.res

recoco/apps/demarches_simplifiees/models.py, recoco/apps/demarches_simplifiees/services.py, recoco/apps/demarches_simplifiees/tests/test_services.py, recoco/apps/demarches_simplifiees/utils.py
Il s'agit de :
On peut désormais utiliser les options des champs DS dans le mapping
EX: 
```python
"champ_Q2hhbXAtMTk3NzQ0NQ": [
{
"value": "option[1]",
"conditions": [
{"value": "edl.acteurs_contact", "tags": ["contact_DDT"]},
],
},
]
```
=> [feat] Prise en compte des options des champs DS et améliorations sur les conditions

recoco/apps/tasks/tests/test_rest_task_followup.py, recoco/apps/tasks/views/rest.py
Il s'agit de :
Un conseiller peut désormais lire les followups d'un projet sur lequel il n'est pas positionné.
https://github.com/betagouv/recommandations-collaboratives/issues/1061
=> [feat] Permission followups conseillers

recoco/apps/projects/static/projects/css/fragments/tasks_modal/modal.scss, recoco/apps/projects/templates/projects/project/fragments/task/task_comment.html, recoco/apps/projects/templates/projects/project/fragments/tasks_modal/task_modal.html, recoco/templates/default_site/tools/editor.html
Il s'agit de :
Correction de l'édition d'un commentaire initial dans la liste des recommandations de l'onglet recommandation d'un projet et dans la fenêtre modal de prévisualisation d'une recommandation.
Dans le premier cas, le contenu du commentaire initial à modifier devenait "text.content" lors de l'édition. Le problème est résolu et affiche maintenant le contenu du commentaire initial.
Dans le second cas, le contenu n'apparaissait pas. Le problème est résolu en cachant le bouton d'édition dans la fenêtre modal pour le commentaire initial. Il aurait été trop long de le corriger en faisant apparaître proprement le message car l'éditeur n'existe pas encore lorsque l'on clique sur éditer et que l'on veut transmettre le contenu du commentaire initial.
Ajout de classe pour le bon placement …
=> [fix] Correction de la modification du commentaire initial d'une recommandation en brouillon

frontend_tests/README.md, frontend_tests/cypress/e2e/header/canCreateANewProject.cy.js, frontend_tests/cypress/e2e/project/collectivity/canCreateAProject.cy.js, frontend_tests/cypress/support/commands.js, recoco/apps/dsrc/templates/dsrc/core/blocks/buttons/button_group.html, recoco/apps/onboarding/templates/onboarding/fragments/form-project.html, recoco/apps/onboarding/templates/onboarding/fragments/form-user.html, recoco/frontend/src/js/components/DsrcFormValidator.js
Il s'agit de :
Mise en place d'une logique pour bloquer la double soumission d'un formulaire.
Resolve #1126
=> [fix] Bug de création des projets en double

recoco/apps/survey/templates/survey/question_details.html
Il s'agit de :
Résolution des problèmes de fichiers edl perdus si validation formulaire sans champ obligatoire rempli.
Les champs de texte (textarea) obligatoire empêche maintenant la validation du formulaire relatif à la question actuelle du questionnaire grâce à l'attribut html required.
resolve #1212
=> Problèmes de fichiers edl perdus si validation formulaire sans champ obligatoire

recoco/apps/projects/templates/projects/project/overview.html
Il s'agit de :
Sur la page de présentation d'un dossier, si aucune question de l'état des lieux ne fait partie de l'onboarding, la section "Complément" est cachée.
resolve #1234 
=> [feat] Cacher la partie complément sur la présentation sous condition

recoco/apps/home/adapters.py, recoco/apps/home/forms.py, recoco/apps/home/tests/test_views.py, recoco/apps/onboarding/forms.py, recoco/frontend/src/js/utils/ajv/schema/ajv.schema.OnboardingSignupForm.js, recoco/frontend/src/js/utils/ajv/schema/ajv.schema.forms.js
Enforce using an uppercase letter, 8 characters and a number for signups.
Il s'agit de :
Dans le cadre de l'homologation de sécurité, nous devons renforcer la complexité des mots de passe.
Cette PR oblige à utiliser une majuscule, une chiffre et au moins 8 caractères.
=> Mots de passe complexes

recoco/apps/projects/templates/projects/project/fragments/navigation/display_select.html, recoco/apps/projects/templates/projects/project/fragments/personal_dashboard/personal_dashboard_map.html, recoco/apps/projects/templates/projects/project/fragments/tasks_inline_kanban/tasks_inline_kanban_filters.html, recoco/apps/projects/templates/projects/project/list-kanban.html, recoco/apps/projects/templates/projects/project/list-map.html, recoco/apps/projects/views/__init__.py, recoco/frontend/src/css/personalAdvisorDashboard.css, recoco/frontend/src/js/components/KanbanProjects.js, recoco/frontend/src/js/components/PersonalAdvisorDashboard.js
Il s'agit de :
Réaffichage du sélecteur de vue sans la vue liste.
Changement de carte dans la vue carte par celle de la vue liste.
Ajout de la barre de filtre de la vue kanban des projets.
Adaptation des filtres à la vue carte et de la carte au changement d'affichage des pins des projets en fonction des filtres.
Environnement de pré-prod souhaité pour s'assurer du bon fonctionnement de la carte et des filtres.
J'ai eu un bug en dév, je pensais que cela venait de mon environnement local, mais j'ai retrouvé le bug dans sentry.
Il est et n'est pas lié à ma PR. Cependant, cela peut entrainer des problèmes d'affichage de la carte.
Resolve #1418
=> Retour de la vue carte avec une nouvelle carte et des filtres projets

recoco/frontend/src/js/components/FeatureAddContact/CreateOrganizationModal.js, recoco/static/css/tools/contact/create-contact-modal.scss, recoco/templates/default_site/tools/contacts/create_organization_modal.html
Il s'agit de :
Ajout d'un message d'erreur lors d'une tentative de création d'une organisation existante sur un autre portail dans la modale de création d'une organisation.
=> [fix] ajout d'un message d'erreur si l'on tente de dupliquer une organisation

recoco/apps/addressbook/rest.py, recoco/apps/addressbook/signals.py, recoco/apps/addressbook/tests/test_rest_organization.py, recoco/frontend/src/js/components/FeatureAddContact/CreateOrganizationModal.js
Il s'agit de :
en front : 
- corrige la prise en compte de l'id du regroupement national
en back
- ne crée pas de regroupement ad hoc si un est mentionné
- change le queryset d'organisation pour renvoyer les orgas sans contact. **A vérifier** je ne sais pas si je ne manque pas un contexte métier
- ajoute des tests pour la création/màj d'organisation
closes #1452
=> fix(addressbook): #1452 ensure orga creation and update uses given org_group

recoco/apps/projects/views/__init__.py
Il s'agit de :
closes #1504
Les user staff, conseillers ou pouvant administrer les projets sont maintenant tous redirigés vers le kanban des projets.
La redirection vers la page tableau de bord conseiller n'est plus active.
=> hotfix(advisor projects view): Redirection vers le kanban des projets

recoco/apps/projects/templates/projects/project/fragments/navigation/display_select.html
Il s'agit de :
Correction de l'url permettant de mettre en exergue l'onglet sélectionné entre kanban et map.
Avant : 
Après :
=> Correction affichage sélecteur kanban / map
