betagouv/recommandations-collaboratives

urbanvitaliz/apps/projects/static/projects/js/access_update.js, urbanvitaliz/apps/projects/templates/projects/project/access_update.html, urbanvitaliz/apps/projects/views/sharing.py
Nouvelle page de partage avec un petit bout de code pour copier le lien de partage.
Modification du principe de redirection après avoir invité quelqu'un pour revenir vers la page de partage.
=> Nouvelle page de partage

urbanvitaliz/apps/projects/templates/projects/project/access_update.html
Changes 
- New wording while sharing
- Replaced dropdown with two cards
=> Update sharing page with new wording

urbanvitaliz/apps/projects/templates/projects/project/knowledge.html
Fixed grey empty box appearing on knowledge when there's no banner.
=> Project : Small grey box fix in knowledge

urbanvitaliz/apps/projects/serializers.py, urbanvitaliz/apps/projects/static/projects/js/kanban_tasks.js, urbanvitaliz/apps/projects/templates/projects/project/fragments/kanban_tasks/preview_modal.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/kanban_tasks/task_item.html
Added a comment_count serializer for displaying only the comments and not all the followups.
Display organization in comments.
Add one to the displayed comment count when there's a ressource attached, because we pretend that this is part of the conversation.
=> Project : Various Kanban Fixes

urbanvitaliz/apps/projects/static/projects/js/kanban_tasks.js, urbanvitaliz/apps/projects/templates/projects/project/access_update.html, urbanvitaliz/apps/projects/templates/projects/project/actions.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/kanban_tasks/kanban_header.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/kanban_tasks/preview_modal.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/kanban_tasks/task_item.html, urbanvitaliz/apps/projects/templates/projects/project/internal_followup.html
Add permission logic in kanban task for external switchtenders
Rename some "aiguilleurs" en "conseiller local"
=> Permission Fixes & Wording (Episode 2)

urbanvitaliz/apps/projects/templates/projects/project/fragments/information_card.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/information_card_description.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/information_card_description_details.html
UrbanVitaliz template : `projects/project/fragments/information_card_description_details.html`
```
{% if title == "Checkbox Group" %}
<div class="d-flex flex-column">
<span class="fw-bolder mb-2">Cartofriche ✅</span>
<p>Ce projet peut être versé sur cartofriche</p>
</div>
{% else %}
<div class="d-flex flex-column">
<span class="fw-bolder mb-2">{% if title == "None" %}Pourquoi nous sollicitez-vous ?{% else %} {{ title }} {% endif %}</span>
<p>{{ content }}</p>
</div>
{% endif %}
```
=> Hotfix - A project information_card_description_details template is now simplified for further customization

urbanvitaliz/apps/onboarding/templates/onboarding/onboarding.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/city_select.html
L'indentation a fucké mon commit : Globalement les 3 changements sont : 
- Ajout d'une ref alpine sur le select de la ville pour changer sa valeur 
- Ajout de la condition pour ré-initaliser la valeur du select avec le {{ form.insee.value }}
- FetchCities et changement de valeur de la ref quand le fetchCities est fini
=> [Onboarding] City is now correctly retrieved in case of captcha error

urbanvitaliz/apps/projects/templates/projects/project/fragments/positioning.html, urbanvitaliz/apps/projects/templates/projects/project/overview.html, urbanvitaliz/frontend/src/css/buttons.css
=> [Project] Positioning call to actions added

urbanvitaliz/apps/projects/templates/projects/project/header.html, urbanvitaliz/frontend/src/css/typography.css
=> [CSS] Boostrap text-info class already used

urbanvitaliz/frontend/src/css/crm.css, urbanvitaliz/templates/default_site/base.html, urbanvitaliz/templates/default_site/header/menu-top-logo.html, urbanvitaliz/templates/default_site/header/menu-top.html
/!\ Mettre à jour recoconseil - branche feature/new-header
PR RECOCONSEILS | feature/new-header -> https://github.com/betagouv/recoco-portails/pull/13
=> [Header] Logged / unlogged version

urbanvitaliz/apps/projects/templates/projects/project/actions.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/kanban_tasks/preview_modal.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/kanban_tasks/task_item.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/positioning.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/positioning_banner.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/sidebar.html, urbanvitaliz/apps/projects/templates/projects/project/overview.html, urbanvitaliz/frontend/src/js/components/Tasks.js
… canManageTasks from user project permissions handled in Tasks.js
=> Retour des différents tests de l'incubateur - new permissions wip

urbanvitaliz/apps/home/templates/home/statistics.html, urbanvitaliz/apps/home/views.py, urbanvitaliz/apps/projects/templates/projects/project/fragments/project_map_modal.html
- Bugfix: titre générique de modal contenant la carte du projet 
- Update: page statistiques UV
=> [front] Wording and stats updates

urbanvitaliz/apps/projects/templates/projects/project/administration_panel.html, urbanvitaliz/apps/projects/templates/projects/project/conversations.html, urbanvitaliz/apps/projects/templates/projects/project/overview.html
carte trello https://trello.com/c/VnMkhhAf/1706-wording-equipe-de-suvi-dans-longlet-pr%C3%A9sentation-et-longlet-conversation
=> [Projects] Équipe de suivi wording fixed -> booooooo

frontend_tests/cypress/e2e/project/tasks/topic/canSeeInlineTaskTopic.cy.js, frontend_tests/cypress/e2e/project/tasks/topic/canSeeKabanTaskTopic.cy.js, urbanvitaliz/apps/projects/templates/projects/project/fragments/tasks_inline/task_item.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/tasks_kanban/task_item.html
https://trello.com/c/SjQDarXb/1733-ajouter-les-th%C3%A9matique-dune-recommandation-dans-la-vue-liste
=> [Tasks] Inline task topic displayed

frontend_tests/cypress/e2e/project/collectivity/canPauseAProjectAsOwner.cy.js, frontend_tests/cypress/e2e/project/collectivity/canQuitProjectAsProjectMember.cy.js, frontend_tests/cypress/e2e/project/collectivity/canSeeEmailReminderAsOwner.cy.js, frontend_tests/cypress/e2e/project/collectivity/canSeeProjectActiveStatus.cy.js, frontend_tests/cypress/e2e/project/collectivity/cantQuitProjectAsProjectOwner.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canPauseAProjectAsStaff.cy.js, frontend_tests/cypress/e2e/project/staff/administration/canQuitProjectAsStaff.cy.js, frontend_tests/cypress/e2e/project/staff/canSeeEmailReminderMessageAsStaff.cy.js, frontend_tests/cypress/e2e/project/switchtender/other/canQuitProjectAsAdvisor.cy.js, frontend_tests/cypress/e2e/project/switchtender/other/canSeeEmailReminderMessageAsAdvisor.cy.js, frontend_tests/cypress/fixtures/projects/projects.json, frontend_tests/cypress/fixtures/projects/projectsMembers.json, frontend_tests/cypress/fixtures/projects/reminders.json, urbanvitaliz/apps/projects/templates/projects/project/fragments/administration/quit_project.html, urbanvitaliz/apps/projects/templates/projects/project/fragments/email_reminder/project_email_reminder.html, urbanvitaliz/frontend/src/css/buttons.css
=> Fixes tests and notifs

urbanvitaliz/frontend/src/css/geocoderBAN.css
=> Fix map address bar

urbanvitaliz/templates/default_site/base.html
Fix uncaught error dans le template de base
=> Fix reference error in base template

README.md, docker/Dockerfile, docker/docker-compose.yml, urbanvitaliz/frontend/vite.config.js
Amélioration de l'environnement Docker : 
- ajout d'un conteneur pour le frontend
- démarrage de l'applicatif automatiquement
- positionnement directement dans le bon répertoire (WORKDIR)
- mise à jour du README
Il faudra à terme faire deux conteneurs avec chacun leur image (techno différente) et ne pas les démarrer en root.
=> [Env Docker] Ajout du frontent et mise à jour de la doc

urbanvitaliz/apps/home/views.py
[Trello ticket](https://trello.com/c/BeVoXWiv/1830-sosp-adaptation-de-la-page-statistiques-%C3%A0-sos-ponts)
=> [feat] SOSPonts adapt statistics page

urbanvitaliz/apps/training/templatetags/training.py
Mini fix ensemble suite visio w/ Guillaume
=> [fix] save challenge acquire with Guillaume

urbanvitaliz/apps/home/templates/home/statistics.html
[Trello Ticket](https://trello.com/c/ZkK1Krp9/1867-peaufiner-la-page-stats-sosp)
Block alignement on UV stats page
=> [style] statistic UV page

urbanvitaliz/frontend/src/js/utils/geocoderBAN.js
=> [fix] geocoderBAN input value assignment

urbanvitaliz/apps/projects/templates/projects/project/fragments/tasks_inline_kanban/tasks_inline_kanban_header.html
[Trello Ticket](https://trello.com/c/mcLyySEY/1800-etq-conseiller-invit%C3%A9-sur-un-projet-je-ne-vois-pas-le-bouton-pour-cr%C3%A9er-de-nouvelles-reco-dans-longlet-recommandations)
=> [fix] Update task management permissions in kanban header

urbanvitaliz/apps/projects/templates/projects/project/fragments/personal_dashboard/personal_dashboard_project_list.html, urbanvitaliz/frontend/src/css/personalAdvisorDashboard.css
#Done
[Trello Ticket](https://trello.com/c/XZwdUgKM/1864-renommer-l%C3%A9tiquette-nouveau-projet-sur-le-tdb-conseiller)
En passant, j'ai amélioré l'affichage lorsque 2 infos étaient affichées :
=> [refactor] project card top information styling + enhance layout

urbanvitaliz/apps/crm/templates/crm/user_item.html, urbanvitaliz/apps/crm/templates/crm/user_list.html
[Trello Ticket](https://trello.com/c/26vHCGxZ/1876-crm-utilisateur-d%C3%A9sativ%C3%A9-barrer-son-nom-dans-les-listes-du-crm)
=> [enhance] Add strikethrough styling for inactive users

urbanvitaliz/apps/addressbook/templates/addressbook/organization_details.html, urbanvitaliz/apps/addressbook/templates/addressbook/widgets/card_contact_horizontal.html, urbanvitaliz/apps/crm/templates/crm/user_details.html, urbanvitaliz/apps/crm/templatetags/phone_filters.py, urbanvitaliz/apps/crm/tests/test_phone_filters.py, urbanvitaliz/apps/projects/templates/projects/project/overview.html, urbanvitaliz/templates/default_site/user/user_card.html
[Trello Ticket](https://trello.com/c/dTfQI1u5/1884-affichage-des-num%C3%A9ros-de-t%C3%A9l%C3%A9phone-ajouter-des-espaces-pour-rendre-lisible)
=> [refactor] Add phone number formatting filter

urbanvitaliz/apps/projects/templates/projects/project/fragments/tasks_modal/feedback_modal.html
[Trello Ticket](https://trello.com/c/UBYzon6N/1873-modale-qui-demande-pourquoi-quand-on-met-une-reco-en-fait-ou-na-modifier-un-texte-r%C3%A9duire-la-hauteur-du-champ-de-texte)
=> [enhance] Update feedback modal label and reduce row number

urbanvitaliz/apps/crm/templates/crm/project_details.html, urbanvitaliz/frontend/src/css/crm.css, urbanvitaliz/static/css/base.scss
[Trello ticket](https://trello.com/c/JvzYPwct/1902-crm-etq-staff-qui-utilise-un-projet-dans-le-crm-je-veux-distinguer-et-comprendre-les-tags-dimpact-et-tags-du-projet)
=> [feat] Change style impact tags and project tags

recoco/templates/default_site/base.html
Delete reference to polyfill.io
=> [hotfix] Remove polyfill for older browsers

recoco/apps/onboarding/templates/onboarding/prefill.html
=> [fix] Increase max length for project name in prefill form

recoco/apps/home/templates/home/contact.html
[Trello ticket](https://trello.com/c/wL3wChyK/1945-mhdf-supprimer-le-template-custom-de-contact)
Va de pair avec [cette PR](https://github.com/betagouv/recoco-portails/pull/49)
=> [style]  add DSFR style to contact page

recoco/frontend/src/css/projectLocation.css
[Trello ticket](https://trello.com/c/2J9zB7nL/1962-bug-daffichage-de-la-map-pour-modifier-la-localisation-qui-dans-certains-cas-est-excessivement-courte)
=> [fix] height map on old firefox

recoco/apps/dsrc/templates/dsrc/core/pages/page_center.html, recoco/apps/dsrc/templates/dsrc/core/pages/page_sidebar.html
- dsrc/base.html template have been deleted, so I removed reference to this template in these two files
=> [hotfix] Remove reference to deleted template dsfr/base.html

recoco/frontend/src/js/components/ModalVideo.js, recoco/frontend/src/js/components/ProjectShare.js, recoco/frontend/src/js/components/StandByProject.js, recoco/frontend/src/js/components/TaskModal.js, recoco/frontend/src/js/store/geolocation.js, recoco/frontend/src/js/store/previewModal.js
Fix modal bootstrap import and initialization
=> [hotfix] Update Bootstrap imports and fix modal initialization

recoco/frontend/src/js/components/Tasks.js, recoco/frontend/src/js/main.js, recoco/frontend/src/js/utils/tooltipInitialization.js, recoco/static/js/tooltip.js, recoco/templates/default_site/base.html
Fix bootstrap initialization of tooltip
=> [fix] bootstrap tooltip init

recoco/apps/crm/templates/crm/project_details.html, recoco/frontend/src/css/crm.css
=> [fix] bug when there are many tags

recoco/apps/home/templates/home/multi_annual_schema.html, recoco/apps/projects/templates/projects/project/fragments/personal_dashboard/personal_dashboard_activity.html
Il s'agit de :
Modification du texte  de la page Schéma pluri-annuel
https://trello.com/c/XBbFZU1w
Modification du titre du TDB conseiller
https://trello.com/c/Y5Ck7ljm
=> feat: quick wording change 

recoco/templates/default_site/base.html
Il s'agit de :
Suppression d'un lien brisé vers un static bootstrap sur la `base.html`
=> [fix] Remove unnecessary Bootstrap JavaScript file

recoco/apps/crm/templates/crm/note.html, recoco/apps/crm/templates/watson/includes/search_result_auth_user.html
Il s'agit de :
Ajout d'une barre rayant le nom des utilisateurs désactivés dans les résultats de recherche et au niveau d'une note dans l'orga du projet.
[Ticket Trello](https://trello.com/c/qw87Bq4I)
=> [CRM] fix - add line through inactive user name

recoco/frontend/src/css/buttons.css
Il s'agit de :
Déplacement de la fenêtre pop bleu de tutoriel pour qu'elle apparaisse en dessous de l'onglet Présentation au lieu d'au dessus.
[Ticket Trello](https://trello.com/c/g5aZK1wq)
=> [tutorial] fix - change position of the button launcher

recoco/apps/home/views.py
Il s'agit de :
Ajout d'une variable resources_count dans le fichier view.py pour l'afficher dans la page statistiques d'ecoquartiers.
Cette pull request est liée avec la pull request 54 de recoco portail : [EQ] feat - add statistics page for EQ
[Trello ticket](https://trello.com/c/DVVwOPi3)
=> [EQ] fix - add variable resources non draft

.gitignore
Il s'agit de :
Des ajouts dans le gitignore pour faciliter le dev en local
=> Update the git ignore file with dev specific things

recoco/apps/addressbook/admin.py, recoco/apps/communication/admin.py, recoco/apps/invites/admin.py, recoco/apps/projects/admin.py, recoco/apps/reminders/admin.py, recoco/apps/survey/admin.py, recoco/apps/tasks/admin.py
Il s'agit de :
Quelques optims ajoutées en parcourant les pages d'admin: ajout de prefetch manquants pour diminuer le nombre de requêtes en base.
=> Quelques améliorations sur les pages d'admin

recoco/apps/crm/tests/test_phone_filters.py
Il s'agit de :
En écrivant des tests je suis tombé sur celui-ci, qui est le seul en mode "TestCase", je l'ai mis à jour.
=> fix: update a "django style" test 

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss
Il s'agit de :
Changement des liens contenu dans un paragraphe pour qu'ils soient soulignés.
[Lien ticket trello](https://trello.com/c/o8hFLiVM)
=> [style] fix - every links into a paragraph are underline

recoco/apps/onboarding/templates/onboarding/fragments/form-project.html
Il s'agit de :
Hotfix commentaire à ne pas afficher (question type cartofriche)
=> [hotfix] display comment if not answers

recoco/frontend/src/js/main.js
Il s'agit de :
Chargement des style Bootstrap et DSFR pour régler l'affichage des ressources, messages
=> [hotfix] change load order style bootstrap dsfr

recoco/apps/onboarding/templates/onboarding/fragments/form-project.html
Il s'agit de :
Suppression des balises hr dans le formulaire de saisine
=> [fix] delete unwanted hr tag, close #370

recoco/apps/metrics/processor.py, recoco/apps/metrics/sql_queries/projects.py, recoco/apps/metrics/sql_queries/recommendations.py, recoco/apps/metrics/sql_queries/resources.py, recoco/apps/metrics/sql_queries/users.py, recoco/apps/metrics/utils.py, recoco/apps/projects/models.py, recoco/settings/common.py
Il s'agit de :
Ce PR ajoute les vues matérialisées pour Users, Projects, Resources et Recommendations
merging closes #387
- [-] Des tests couvrant le code changé ont été ajoutés/modifiés
=> Metrics : ajout des vues materialisées

recoco/frontend/src/js/utils/ajv/schema/ajv.schema.PrefillProjectForm.js
Il s'agit de :
Suppression de la limite sur le champ description d'un projet lors du prefill 
close #437
=> [fix] remove limit on description field on prefill process

.gitignore, recoco/apps/resources/views.py, recoco/apps/survey/templatetags/survey.py, recoco/apps/tasks/views/rest.py
Il s'agit de :
- ménage
- ignorer les scripts locaux
=> fix: cleanup and more

recoco/apps/home/static/home/css/cms/page-text.css, recoco/apps/pages/templates/pages/simple_page.html
Il s'agit de :
Ajout d'un fichier de style spécifique pour les pages de texte plein ajouté à la page "simple_page.html"
[Lien ticket Github project](https://github.com/betagouv/recommandations-collaboratives/issues/381)
- [] Je souhaite un déploiement en préproduction
=> [CMS] feat - adding style file css to simple page

recoco/templates/default_site/reversion-compare/compare_generic_add.html
Il s'agit de :
Ajout du template manquant menant à une erreur 500 sur la comparaison de ressource
@glibersat je pense que c'était ce qu'il manquait, j'ai été le chercher directement dans le repo du package (et il y a surement d'autre template que nous n'avons pas)
Link to [#383](https://github.com/betagouv/recommandations-collaboratives/issues/383)
=> [fix] missing template

recoco/apps/metrics/processor.py
=> fix: get rid of materialized views prefix

recoco/apps/metrics/sql_queries/projects.py
Il s'agit de :
Fix des metrics sur les projets
=> fix: metrics on projects

recoco/apps/projects/tests/test_projects.py, recoco/apps/projects/views/export.py
Il s'agit de :
Ajout des tags du CRM (configurés dans site config) dans l'export csv des projets.
=> feat: dynamically add annotation tags in the csv export of projects

README.md
Il s'agit de :
Mise à jour du lien "En savoir plus"
=> fix: update obsolete link in README file

recoco/apps/home/management/commands/create_site.py, recoco/apps/home/migrations/0015_create_site_groups_and_permissions_20230220_1329.py, recoco/apps/home/tests/test_commands.py, recoco/apps/home/tests/test_views.py, recoco/apps/home/utils.py
Il s'agit de :
Ajout d'une commande pour la création d'un nouveau portail
=> feat: add create site management command

docker/docker-compose.yml, makefile, recoco/__init__.py, recoco/worker.py, requirements.txt
Il s'agit de :
Mise en place de celery, en préparation de https://github.com/betagouv/recommandations-collaboratives/pull/391
=> feat: Celery setup

recoco/apps/metrics/sql_queries/projects.py
Il s'agit de :
Ajout d'un distinct pour éviter la multiplication des tags quand il y a plusieurs messages dans le projet.
=> fix(project metrics): avoid tags duplication

recoco/apps/addressbook/templates/addressbook/contact_create.html, recoco/apps/addressbook/templates/addressbook/contact_update.html, recoco/apps/addressbook/templates/addressbook/organization_create.html, recoco/apps/addressbook/templates/addressbook/organization_details.html, recoco/apps/addressbook/templates/addressbook/organization_list.html, recoco/apps/addressbook/templates/addressbook/organization_update.html, recoco/apps/projects/templates/projects/project/location.html, recoco/apps/projects/templates/projects/project/note_create.html, recoco/apps/projects/templates/projects/project/note_update.html, recoco/apps/projects/templates/projects/project/topics.html, recoco/apps/projects/templates/projects/project/update.html, recoco/apps/resources/templates/resources/bookmark/create.html, recoco/apps/resources/templates/resources/resource/create.html, recoco/apps/resources/templates/resources/resource/delete.html, recoco/apps/resources/templates/resources/resource/fragments/breadcrumb.html, recoco/apps/resources/templates/resources/resource/update.html, recoco/apps/survey/templates/survey/editor/choice/create.html, recoco/apps/survey/templates/survey/editor/choice/update.html, recoco/apps/survey/templates/survey/editor/question/create.html, recoco/apps/survey/templates/survey/editor/question/results.html, recoco/apps/survey/templates/survey/editor/question/update.html, recoco/apps/survey/templates/survey/editor/question_set/create.html, recoco/apps/survey/templates/survey/editor/question_set/details.html, recoco/apps/survey/templates/survey/editor/question_set/update.html, recoco/apps/survey/templates/survey/editor/survey/details.html, recoco/apps/survey/templates/survey/question_details.html, recoco/apps/tasks/templates/tasks/task/task_followup_update.html
Il s'agit de :
Correction du tag causant un mauvais affichage du fil d'ariane. 
close #435
=> [fix] use ul tag for breadcrumb

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/templates/default_site/header/dropdown-menu-notifications.html, recoco/templates/default_site/user/user_card.html
Il s'agit de :
Correction de régressions : curseur au survol et libellé d'une notification d'une nouvelle recommandation
=> [Notifications] Corrections post MEP

recoco/templates/default_site/reversion-compare/action_list_partial.html
Il s'agit de :
Amélioration de l'ui pour la fonction de comparaison de version.
=> [refactor] enhance table comparaison view

recoco/apps/home/static/home/css/cms/page-showcase.css, recoco/apps/pages/templates/pages/showcase_page.html
Il s'agit de :
Création du template de la page showcase et du fichier de style associé
[Lien ticket Trello associé](https://github.com/betagouv/recommandations-collaboratives/issues/409)
=> [CMS] feat - add template(V0.7) and css file for showcase page

recoco/static/css/menu-top.scss, recoco/templates/default_site/header/menu-top-secondary.html, recoco/templates/default_site/header/menu-top.html
Il s'agit de :
Correction du bug d'affichage du menu pour les éléments resssources et méthodologie qui n'étaient pas centrés.
Refacto du css inline et des classes utilisées pour harmoniser le header et le code.
[Cette PR est liée à cette PR sur multisites.](https://github.com/betagouv/recoco-portails/pull/79)
=> [Hotfix] refacto css and fix menu vertical alignment

recoco/apps/crm/templates/crm/projects_low_reach.html, recoco/apps/crm/templates/crm/site_dashboard.html, recoco/apps/crm/tests/test_dashboard.py, recoco/apps/crm/urls.py, recoco/apps/crm/views.py
Il s'agit de :
Page supplémentaire pour aider à la relance des collectivités
=> [crm] Ajout d'une page pour trouver les projets avec peu d'impact

recoco/apps/dsrc/templates/dsrc_crispy_forms/layout/baseinput.html
Il s'agit de :
Hotfix du Dsrc form
=> [hotfix] dsrc form

.github/workflows/django.yml, makefile, recoco/apps/home/admin.py, recoco/apps/projects/__init__.py, recoco/apps/projects/views/sharing.py, recoco/apps/survey/__init__.py, recoco/apps/tasks/__init__.py
Il s'agit de :
Ajout d'une action dans le CI pour vérifier les hook du precommit
=> chore: check pre-commit hooks in CI

recoco/templates/default_site/header/menu-top.html
Il s'agit de :
Ajout d'un padding sur l'axe y sur le menu du header par défaut des portails.
=> [fix] update menu padding

frontend_tests/cypress/e2e/auth/loginWithoutUi.cy.js, frontend_tests/cypress/e2e/header/canAccessNotificationMenuAndManageNotifications.cy.js, frontend_tests/cypress/e2e/project/overview/canSeeEDLResponseOnProjectOverview.cy.js, frontend_tests/cypress/e2e/project/tasks/canSeeKanbanTasks.cy.js, frontend_tests/cypress/e2e/project/tasks/canSwitchBetweenTasksViews.cy.js, frontend_tests/cypress/e2e/project/tasks/previewModal/canEditMessageDraftTask.cy.js, frontend_tests/cypress/e2e/project/tasks/previewModal/canOpenPreviewModal.cy.js, frontend_tests/cypress/e2e/project/tasks/previewModal/canPostAFollowup.cy.js, frontend_tests/cypress/e2e/project/tasks/previewModal/canSeeFollowupCreationDate.cy.js, frontend_tests/cypress/e2e/project/tasks/previewModal/cantCommentDraftTask.cy.js, recoco/static/css/menu-top.scss, recoco/templates/default_site/header/menu-top-secondary.html
Il s'agit de :
Correction et mise à jour de différents tests front-end en échec
=> [fix] test front-end

pyproject.toml, recoco/apps/dsrc/templatetags/dsrc_tags.py, recoco/apps/home/management/commands/create_site.py, recoco/apps/home/migrations/0015_create_site_groups_and_permissions_20230220_1329.py, recoco/apps/home/rest.py, recoco/apps/home/views.py, recoco/apps/metrics/processor.py, recoco/apps/projects/views/rest.py, recoco/apps/projects/views/sharing.py, recoco/apps/tasks/forms.py, recoco/utils.py
Il s'agit de :
Amélioration de la qualité de code, en appliquant la rule B de Ruff
https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
=> chore: apply the ruff rule B (bugbear)

frontend_tests/cypress/e2e/project/staff/kanban/canSearchAndDisplayProject.cy.js, recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/apps/projects/static/projects/css/kanban.scss, recoco/apps/projects/static/projects/css/searchbar.scss, recoco/apps/projects/templates/projects/project/fragments/personal_dashboard/personal_dashboard_header.html, recoco/apps/projects/templates/projects/project/fragments/personal_dashboard/personal_dashboard_project_filters.html, recoco/apps/projects/templates/projects/project/fragments/region_filter.html, recoco/apps/projects/templates/projects/project/fragments/search_bar.html, recoco/apps/projects/templates/projects/project/list-kanban.html, recoco/frontend/package.json, recoco/frontend/src/css/regionFilter.css, recoco/frontend/src/js/apps/advisorDashboard.js, recoco/frontend/src/js/components/KanbanProjects.js, recoco/frontend/src/js/components/PersonalAdvisorDashboard.js, recoco/frontend/src/js/store/tasksData.js, recoco/frontend/yarn.lock
Il s'agit de :
- Ajout d'une barre de recherche sur le kanban
- Uniformisation de la navigation entre les pages kanban, liste projet et carte
- Uniformisation du header de recherche sur la page carte 
- Ajout des test de bout en bout
Close #441 et #429
=> Feat/kanban searchbar#441

recoco/apps/onboarding/forms.py
Il s'agit de :
Modification des champs du formulaire d'onboarding Description et projet et ajout d'un texte d'aide.
[Lien ticket github 1](https://github.com/betagouv/recommandations-collaboratives/issues/416)
[Lien ticket github 2](https://github.com/betagouv/recommandations-collaboratives/issues/427)
=> [fix] update form label and help text

recoco/apps/crm/templates/crm/project_details.html, recoco/frontend/src/css/crm.css
Il s'agit de :
Correction de l'affichage du profil des utilisateurs dans la partie CRM
Close #306
=> [style] fix crm profil user

recoco/apps/crm/templates/crm/organization_update.html
Il s'agit de :
Changement de wording sur le bouton d'enregistrement d'une organisation dans le CRM. 
Close #400
=> [wording] edit text button update orga

recoco/apps/crm/templates/crm/project_details.html
Il s'agit de :
Correction de l'affichage du profil des utilisateurs dans la partie CRM
Close #306
=> [test] deactivate linter that break test

frontend_tests/cypress/e2e/project/onboarding/canCreateAProjectIfConnected.cy.js, frontend_tests/cypress/support/commands.js, recoco/apps/onboarding/forms.py, recoco/apps/onboarding/views.py, recoco/frontend/src/js/utils/ajv/schema/ajv.schema.OnboardingProjectForm.js, recoco/frontend/src/js/utils/ajv/schema/ajv.schema.PrefillProjectForm.js
Il s'agit de :
L'adresse n'est plus obligatoire pour la création d'un projet. Si le champ adresse n'est pas rempli, on ne propose à l'utilisateur de localiser le projet.
Close #436
=> Feat/optional geoloc project#436

frontend_tests/cypress/e2e/project/overview/canSeeDisabledInvitationButton.cy.js, frontend_tests/cypress/support/commands.js, recoco/apps/projects/templates/projects/project/list.html, recoco/apps/projects/templates/projects/project/overview.html
Il s'agit de :
Affichage d'un bouton (désactivé) pour inviter un membre collectivité pour les conseiller·e locale non affecté à un projet.
Close #340
=> Fix/btn invit coll#340

recoco/apps/home/models.py
Il s'agit de :
Modification du wording de l'interface configuration d'un site.
=> [refactor] wording form site config

recoco/frontend/src/js/components/Task.js, recoco/frontend/src/js/store/previewModal.js, recoco/frontend/src/js/utils/api.js
Il s'agit de :
Résolution d'un bug qui empêchait la consommation de notifications dans les recommandations.  
Close #474
=> [fix] collectivity member can now consumme reco

recoco/frontend/src/js/store/previewModal.js
Il s'agit de :
Amélioration : suppression du `await` pour rendre le code non bloquant
=> [fix] remove await in api call

recoco/frontend/src/css/crm.css
Il s'agit de :
Bug visuel corrigé dans l'affichage des profils dans le CRM.
Close #306 
- [] Mon code est auto-documenté ou la documentation a été mise à jour/créée
- [] La gestion du multi-portail a été prise en compte
=> [fix] css broken profil in crm

recoco/apps/dsrc/templates/dsrc/core/blocks/inputs/input_checkbox.html
Il s'agit de :
Correction du comportement du composant checkbox pour DSRC
=> [fix] checkbox dsrc init value

recoco/static/css/menu-top.scss
Il s'agit de :
Dans le menu déroulant des projets pour un conseiller (barre de menu):
- Remplacement du nom du projet par la commune
- Remplacement de l'adresse par le nom du projet
- Correction de la hauteur du dropdown
Cette PR va de paire avec [celle ci ](https://github.com/betagouv/recoco-portails/pull/85) 
Close #417
=> [fix] style menu dropdown

recoco/apps/projects/views/__init__.py
Il s'agit de :
Correction du filtre de la vue carte suite au changement de model multiportail. 
(Fix spontané)
=> [fix] update filter in view - multiportail status impact

recoco/apps/projects/serializers.py, recoco/apps/projects/tests/test_rest.py, recoco/apps/projects/views/rest.py, recoco/apps/webhook/tests/test_signals.py, recoco/rest_api/filters.py
Il s'agit de :
- ajout d'un filtre par tags dans l'API qui liste les projets
- ajout d'un champ `tags` dans le serializer
=> feat: filter projects by tags

recoco/apps/webhook/signals.py, recoco/apps/webhook/tests/test_signals.py, recoco/settings/common.py
Il s'agit de :
- prise en compte des modification des tags des projets
- ajouts de tests
=> feat: handle project tags changes in the webhook process

recoco/apps/onboarding/forms.py
Il s'agit de :
Changement du label pour l'organisation et de son helptext ainsi que l'helptext de l'adresse dans la saisine.
[Lien du ticket Github Project associé](https://github.com/betagouv/recommandations-collaboratives/issues/545)
- [] L'ensemble des tests front et back sont au vert
=> [fix] update labels and helptexts for the saisine #545

recoco/apps/projects/serializers.py, recoco/apps/projects/tests/test_rest.py, recoco/apps/webhook/tests/test_signals.py
Il s'agit de :
Besoin de cette info dans Grist
=> feat: add location field to project API payload

recoco/frontend/src/js/components/KanbanProjects.js
Il s'agit de :
Amélioration de la recherche dans le kanban : 
- Plus de tolérance sur la recherche (accent, espace, lettre manquante, inversée etc...)
Close #540 #547
=> [fix] update search in kanban

recoco/apps/projects/static/projects/css/kanban.scss, recoco/apps/projects/templates/projects/project/list-kanban.html
Il s'agit de :
Suppression de l'organisation dans les cartes du kanban
Close #546
=> [fix] remove orga from project in kanban

recoco/frontend/vite.config.js
Il s'agit de :
Config vite pour pouvoir servir correctement les médias provenant des librairies (icon, fonts etc)
=> [fix] vite setup - serve assets from dependencies (finaly !!!)

recoco/apps/dsrc/templates/dsrc/core/blocks/buttons/button.html, recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/apps/projects/static/projects/css/project_moderation.scss, recoco/apps/projects/templates/projects/moderation.html, recoco/apps/projects/templates/projects/project/fragments/advisor_note.html, recoco/apps/projects/templates/projects/project/fragments/information_card.html, recoco/apps/projects/templates/projects/project/fragments/owner/owner-details.html, recoco/apps/projects/templates/projects/project/fragments/project_owner.html, recoco/apps/projects/templates/projects/project/overview.html, recoco/apps/projects/templates/projects/projects_moderation.html, recoco/apps/projects/tests/test_projects.py, recoco/apps/projects/urls.py, recoco/apps/projects/views/__init__.py, recoco/templates/default_site/header/menu-top-secondary.html, recoco/templates/default_site/header/menu-top.html
Il s'agit de :
Will close #494
=> Feat/refonte moderation project#494

recoco/apps/projects/admin.py, recoco/apps/projects/models.py
Il s'agit de :
Améliorations de la age admin des notes:
- optim du nombre de requêtes
- visibilté/filtre des notes marquées comme supprimées
- ajout d'infos dans la liste des notes
- ajout de filtres
=> feat: improve the notes admin page

recoco/apps/projects/static/projects/css/project_navigation.css, recoco/apps/projects/templates/projects/project/header.html, recoco/apps/projects/templates/projects/project/navigation.html, recoco/templates/default_site/base.html
Il s'agit de :
- Correction du h1 général
- Page projet : 
- Ajout d'un h2 (titre projet)
- Ajout de h3 (tabs projet)
=> [refactor] add h1, h2, h3 on project page

recoco/apps/projects/templates/projects/project/overview.html
Il s'agit de :
Affichage des réponse aux question de l'onboarding sur la page de présentation d'un projet
=> [fix] overview presenting answer

recoco/apps/projects/templates/projects/project/fragments/information_card_description.html, recoco/apps/survey/templatetags/survey.py
Il s'agit de :
Chargement de la page projet même avec l'ancienne version de l'onboarding (et sans réponse)
=> [fix] load project when no answer

recoco/frontend/.eslintrc.js, recoco/frontend/src/js/components/MapEditor.js, recoco/frontend/src/js/components/MapViewerInteractive.js, recoco/frontend/src/js/store/geolocation.js, recoco/frontend/src/js/utils/map.js
Il s'agit de :
Implémentation de la fonctionnalité de centrage de la map de l'EDL, lorsqu'une adresse est saisie lors de l'étape d'onboarding
Resolve #350
=> [feat] center map when adresse is filled at EDL

recoco/apps/projects/static/projects/css/project_moderation.scss, recoco/apps/projects/templates/projects/project/fragments/information_card.html, recoco/apps/projects/templates/projects/project/fragments/information_card_description.html, recoco/apps/projects/templates/projects/project/fragments/project_owner.html, recoco/apps/projects/templates/projects/projects_moderation.html, recoco/apps/survey/templates/survey/widgets/qs_summary_card.html
Il s'agit de :
Dans l'écran de modération : 
- Correction de l'affichage des questions de l'onboarding 
- Amélioration de l'alignement des blocs
Resolve #627 #619
=> [fix] add summary and context in moderation page

recoco/apps/home/static/home/css/cms/page-showcase.css
Il s'agit de :
Ajout d'une couleur de h1 pour permettre au titre des pages cas d'usage d'être bien visible.
=> [fix] update h1 color to make it readable in the showcase page

recoco/frontend/src/js/utils/map.js
Il s'agit de :
- Correction de l'adresse de l'API pour le centrage de la map à l'étape de l'EDL
Resolve #350
=> [fix] typo in api url

recoco/apps/demarches_simplifiees/adapters/42113.py
Il s'agit de :
Ajout de la config DS de mapping, afin de faire fonctionner la démarche `prefecture-du-doubs-demande-de-versement-des-subventions-detr-dsil-fnadt-dpv`.
=> feat: adding a basic mapping to make DS  #42113 work

recoco/apps/projects/static/projects/js/action_pusher.js, recoco/apps/projects/templates/projects/project/fragments/tasks_inline/task_item.html
Il s'agit de :
Dans le pousse-reco lors de la recherche d'une ressource liée à une Démarche Simplifiée, un badge informatif apparait.
=> [fix] update search fields for Démarches Simplifiées

pyproject.toml, recoco/settings/testing.py
Il s'agit de :
Permettre la surcharge de settings pour les tests seulement.
=> Adding a dedicated settings file for test

recoco/apps/resources/static/resources/resources.scss
Il s'agit de :
Mise à jour du style pour afficher le département choisi dans la recherche des ressources
=> [fix] show selected department in search ressource page

docs/conf.json, docs/conf.py, docs/index.rst, docs/install.rst, docs/js_components.rst, docs/models.rst, docs/permissions.rst, docs/terminology.rst, recoco/frontend/src/js/components/PreviewModal.js, requirements-dev.txt
=> [doc] add django and js support to sphinx

recoco/apps/projects/templates/projects/project/detail-ro.html, recoco/apps/projects/views/sharing.py
Il s'agit de :
Ajout des variables de sessions dans la vue Python
Resolve #654
=> [fix] sharing page EDL

.pre-commit-config.yaml, makefile, pyproject.toml, recoco/apps/crm/views.py, recoco/apps/home/forms.py, requirements-dev.txt, scripts/tp2t.py
Il s'agit de :
- bump precommit hooks version
- new precommit hook `check-yaml`
- make ruff run bandit
=> chore: update precommit hooks and more

recoco/frontend/src/js/components/MapViewerInteractive.js, recoco/frontend/src/js/components/MapViewerStatic.js
Il s'agit de :
Correction d'affichage de la modal contenant la map d'un projet
=> [fix] project overview open modal map

recoco/static/css/base.scss, recoco/static/css/header/header.scss, recoco/templates/default_site/header/menu-top-secondary.html
Il s'agit de :
Résolution du bug qui empêchait nos utilisateurs de naviguer vers un projet à partir de la liste déroulante.
=> [hotfix] click project list

recoco/apps/projects/templates/projects/project/fragments/information_card_description.html
Il s'agit de :
Les notes internes s'affichent maintenant correctement.
Resolve #716 
=> [fix] internal note render

recoco/apps/metrics/management/commands/update_materialized_views.py, recoco/apps/metrics/processor.py, recoco/apps/metrics/sql_queries/projects.py, recoco/apps/metrics/sql_queries/user_activity.py, recoco/apps/metrics/sql_queries/users.py, recoco/apps/metrics/tests/test_processor.py, recoco/settings/common.py
=> Ajout de métriques supplémentaires

recoco/apps/survey/templates/survey/question_details.html, recoco/frontend/src/js/components/Tutorial.js
Il s'agit de :
Modification des critères d'apparition de la fenêtre modale du tutoriel de l'état des lieux.
De cette manière, il n'apparaît plus si on ferme la fenêtre ou clique en dehors de cette dernière.
La première apparition ne dépend plus du projet actif.
=> [fix] update tuto edl recurrence

recoco/apps/projects/views/__init__.py
Il s'agit de :
Correction des variables nécessaires à l'envoi du mail lors du partage d'un projet entre portail.
=> [fix] variables digest mail EDL

recoco/apps/projects/context_processors.py, recoco/templates/default_site/header/dropdown-menu-notifications.html
Il s'agit de :
Dans le popup de notif le projet est maintenant affiché lorsque nécessaire (notif de nouveau message, ou de modification d'EDL) 
Resolve #625 #634
=> Fix/notif edl#634

recoco/templates/default_site/footer.html
Il s'agit de :
Ajout d'un lien dans le footer menant vers la page des cas d'usage lorsque l'utilisateur.ice n'est pas connecté.e.
Cette PR est liée avec [cette PR de multisite](https://github.com/betagouv/recoco-portails/pull/99).
=> [feat] add usecase page list to footer

recoco/apps/projects/templates/projects/project/actions.html, recoco/apps/projects/templates/projects/project/knowledge.html, recoco/apps/projects/templates/projects/project/overview.html
=> ETQ staff, je suis censé pouvoir voir tous les projets sans m'affecter 

recoco/apps/projects/templates/projects/project/fragments/share/public_share_modal.html
Il s'agit de :
Ajout du chargement du fichier JS permettant de charger les variables nécessaires au fonctionnement de la fenêtre modal pour partager l'état des lieux d'un projet.
=> [fix] display modal to share edl

frontend_tests/cypress/e2e/project/collectivity/canSeeGeneralInformation.cy.js, notebooks/dsrc_doc/DsrcButton.py, recoco/apps/home/templates/home/accessibility.html, recoco/frontend/src/js/main.js, recoco/frontend/src/js/store/geolocation.js
=> Suppression des console.log 

recoco/frontend/src/js/store/previewModal.js
=> Le clic sur la notif d'une reco ouvre la modal de prévisualisation

recoco/apps/projects/static/projects/css/kanban.scss
Il s'agit de :
Modification de la hauteur du tableau kanban des projets pour qu'il s'adapte mieux à la taille de l'écran.
Close #632
=> [feat] update kanban height

recoco/apps/projects/templates/projects/project/actions.html, recoco/apps/tasks/forms.py, recoco/frontend/src/css/select-a11y.scss, recoco/frontend/src/js/apps/selectSearchable.js, recoco/frontend/src/js/components/SelectSearchable.js, recoco/frontend/src/js/utils/select-a11y.js, recoco/templates/default_site/tools/select_searchable.html
=> Dans le pousse reco, les projets récemment visités apparaissent en premières suggestions

recoco/apps/projects/static/projects/css/project.scss, recoco/apps/projects/templates/projects/project/overview.html, recoco/static/css/menu-top.scss
Il s'agit de :
La liste déroulante de l'entête est plus large et les info importantes du projet sont affichées en plus des tags.
Resolve #745
=> Meilleurs visibilité des infos du projet + tags

recoco/apps/home/signals.py, recoco/apps/home/views.py, recoco/apps/projects/signals.py, recoco/apps/projects/tests/test_notes.py, recoco/apps/projects/tests/test_utils.py, recoco/apps/projects/utils.py, recoco/apps/projects/views/administration.py, recoco/apps/tasks/signals.py
Il s'agit de :
closes #705 
closes #706
=> Amélioration des notifications multi-portails

recoco/apps/onboarding/templates/onboarding/fragments/form-project.html, recoco/frontend/src/js/components/FieldValidator.js
=> Résolution du bug d'affichage du champ en erreur sur la saisine

recoco/frontend/src/js/store/showRole.js, recoco/templates/default_site/user/user_card.html
=> fix: get rid of mistaken words

publiccode.yml
Il s'agit de :
Ajout du bon lien pour le logo dans publiccode.yml.
=> [fix] publiccode.yml: Use the correct logo path

recoco/settings/common.py, requirements.txt
Il s'agit de :
Ajout de la dépendance [django-waffle](https://waffle.readthedocs.io/en/stable/index.html), afin de pouvoir ajouter des flags sur les fonctionnalités en production.
=> Adding dependency django-waffle

recoco/apps/demarches_simplifiees/tasks.py, recoco/apps/demarches_simplifiees/tests/test_tasks.py
Il s'agit de :
Erreur dans la tâche qui créer les dossier DS, dans le cas où une recommandation n'a pas de ressource associée.
https://github.com/betagouv/recommandations-collaboratives/issues/665
=> fix: sentry issue 119619

README.md, recoco/apps/projects/templates/projects/project/fragments/advisor_gravatar_list_item.html, recoco/apps/projects/templates/projects/project/fragments/only_my_projects_filter.html, recoco/apps/projects/templates/projects/project/list-kanban.html, recoco/apps/projects/templates/projects/projects_moderation.html, recoco/frontend/.eslintrc.js, recoco/frontend/babel.config.js, recoco/frontend/config/jest/fileTransform.js, recoco/frontend/jest.config.js, recoco/frontend/package.json, recoco/frontend/src/js/apps/boardProjects.js, recoco/frontend/src/js/components/GravatarCache.js, recoco/frontend/src/js/components/KanbanProjects.js, recoco/frontend/src/js/store/projects.js, recoco/frontend/src/js/utils/localStorageMgmt.js, recoco/frontend/tests/localStorageMgmt.spec.js, recoco/frontend/vite.config.js, recoco/frontend/yarn.lock
Il s'agit de :
Mise en place d'un cache pour les gravatars
=> [Feat] Mise en place d'un cache sur les gravatar

recoco/apps/home/templates/home/accessibility.html, recoco/apps/home/templates/home/privacy.html, recoco/apps/onboarding/templates/onboarding/prefill-project.html, recoco/apps/onboarding/templates/onboarding/prefill-user.html, recoco/apps/projects/templates/projects/project/actions.html, recoco/apps/projects/templates/projects/project/actions_embed.html, recoco/apps/projects/templates/projects/project/fragments/administration/stand_by_project.html, recoco/apps/projects/templates/projects/project/fragments/share/invite_member.html, recoco/apps/projects/templates/projects/project/fragments/tasks_kanban/kanban_header.html, recoco/apps/projects/templates/projects/project/navigation.html, recoco/apps/projects/templates/projects/project/overview.html, recoco/frontend/src/js/config/tutorials.json, recoco/templates/default_site/actstream/action.html
=> [refactor] Changement de wording pour supprimer le terme collectivité

recoco/apps/projects/static/projects/css/fragments/personnal_dashboard/personnal_dashboard.scss, recoco/apps/projects/templates/projects/project/fragments/personal_dashboard/personal_dashboard_project_filters.html, recoco/frontend/src/js/apps/advisorDashboard.js
Il s'agit de :
Résolution du bug d'affichage des gravatar + affichage du filtre
Resolve #802
=> [Hotfix] Bug d'affichage dans le tableau de bord des conseillers

recoco/apps/metrics/management/commands/update_materialized_views.py, recoco/apps/metrics/processor.py, recoco/apps/metrics/tests/test_processor.py, recoco/settings/common.py
Il s'agit de :
related to #694 
=> [Metrics] Ajout de la possibilité de surcharger les propriétaires des schémas

recoco/settings/production.py
Il s'agit de :
Mise en place de sentry pour la partie python (django & celery), en prod uniquement.
=> [chore] Sentry sdk setup in python part

frontend_tests/cypress/e2e/tools/tutorial/projectOverviewTutorial.cy.js, frontend_tests/cypress/fixtures/settings/challengeDefinition.json, recoco/apps/projects/templates/projects/project/fragments/project_banner/join_project_banner.html, recoco/frontend/src/js/config/tutorials.json, recoco/templates/default_site/tutorial/tutorial_hint.html
Il s'agit de :
Ajout d'une série de tests couvrant la fonctionnalité de tutoriel pour la présentation de l'interface de gestion d'un projet.
=> [feat] add test for overview project tutorial

frontend_tests/cypress/e2e/project/collectivity/canFillUpsurvey.cy.js, recoco/apps/projects/templates/projects/project/fragments/survey_grid.html
Il s'agit de :
Correction du test visant à vérifier le bon fonctionnement du tutoriel de l'état des lieux ainsi que le remplissage de l'état des lieux.
=> [fix] correct file canFillUpSurvey test

recoco/apps/projects/templates/projects/project/conversations.html
Il s'agit de :
Augmentation de la limite du nombre de messages dans la conversation de 20 à 100
=> [fix] Augmentation de la limite du nombre de messages dans la conversation

pyproject.toml, recoco/apps/social_account/adapters.py, recoco/apps/social_account/provider.py, recoco/settings/common.py, recoco/settings/development.py.example
Il s'agit de :
Ajustements sur le flow d'authentification proconnect.
=> [feat]  proconnect adjustments

recoco/templates/default_site/account/login.html, recoco/templates/default_site/account/password_reset.html
=> [refactor] Amélioration visuelle Proconnect 

recoco/frontend/src/js/components/CitySelect.js
=> [fix] Saisine retour d'erreur erronée

frontend_tests/cypress/e2e/project/tasks/canPublishDraftTask.cy.js, recoco/frontend/src/js/components/SelectSearchable.js, recoco/frontend/src/js/utils/select-a11y.js
=> [feat] Pousse-reco - Sélection automatique du dernier projet visité

recoco/apps/social_account/adapters.py, recoco/settings/common.py
Il s'agit de :
On désactive le signup proconnect pour le moment
=> [fix] Proconnect disable signup

recoco/apps/projects/templates/projects/project/list-kanban.html, recoco/apps/projects/templates/projects/projects_moderation.html
Il s'agit de :
Nettoyage de code mort
Resolve #808
=> [refactor] Suppression de code mort

frontend_tests/cypress/e2e/project/tasks/previewModal/canPostAFollowup.cy.js, frontend_tests/cypress/support/commands.js, recoco/apps/projects/templates/projects/project/fragments/tasks_modal/task_modal.html, recoco/frontend/src/js/components/PreviewModal.js
=> [fix] Affichage de la personne ayant publié le commentaire sur les reco  

frontend_tests/cypress/support/views/project.js, recoco/apps/projects/templates/projects/project/fragments/email_reminder/project_email_reminder.html
=> [fix] email reminder

.pre-commit-config.yaml, pyproject.toml, recoco/apps/metrics/management/commands/update_materialized_views.py, recoco/apps/metrics/processor.py, recoco/apps/metrics/sql_queries/projects.py, recoco/apps/metrics/sql_queries/recommendations.py, recoco/apps/metrics/sql_queries/resources.py, recoco/apps/metrics/sql_queries/user_activity.py, recoco/apps/metrics/sql_queries/users.py, recoco/apps/metrics/tests/sql_queries/view_test_django_qs.py, recoco/apps/metrics/tests/sql_queries/view_test_raw_sql.sql, recoco/apps/metrics/tests/test_processor.py, recoco/apps/metrics/utils.py, recoco/settings/common.py, scripts/metrics_diff.sh
Il s'agit de :
Refacto du mécanisme des vues matérialisées pour metabasbe, afin de pouvoir créer des vues cross-sites et par site.
=> [feat] Mt views refacto

recoco/apps/metrics/management/commands/update_materialized_views.py, recoco/apps/metrics/processor.py, recoco/apps/metrics/tests/test_processor.py, recoco/settings/common.py
=> [fix] Site db schema owner overriding

recoco/apps/projects/serializers.py, recoco/apps/projects/tests/test_rest.py
Il s'agit de :
Ajout du champ `project_sites`.
=> [feat] Updating payload of the api userprojectstatus

recoco/apps/projects/models.py, recoco/apps/projects/tests/test_models.py, recoco/apps/projects/views/detail.py, recoco/apps/projects/views/documents.py
Il s'agit de :
4 annotations ajoutées sur les queryset de Projet:
- action_notifications_count
- conversation_notifications_count
- private_conversation_notifications_count
- document_notifications_count
=> [feat] Project notifications counts

recoco/apps/projects/templates/projects/project/navigation.html
Il s'agit de :
Modification du texte de l'encart permettant de sélectionner un rôle (observateur ou conseiller).
=> [fix] change role selector wording

recoco/apps/home/templates/home/privacy.html
Il s'agit de :
Modification des informations relatives aux cookies pour y ajouter les informations des cookies de dailymotion.
Cete PR est liée avec [celle du multisites.](https://github.com/betagouv/recoco-portails/pull/109)
=> [feat] add dailymotion cookies informations

recoco/frontend/src/js/components/User.js
=> [fix] faute d'accord dans un toast

recoco/apps/projects/templates/projects/project/fragments/survey_grid.html
=> [fix] typo in survey page

recoco/apps/metrics/management/commands/update_materialized_views.py, recoco/apps/metrics/tests/base.py, recoco/apps/metrics/tests/test_command.py, recoco/apps/metrics/tests/test_processor.py
Il s'agit de :
Make the script in charge of creating the materialized views create also the missing roles
=> [feat] Create the missing roles by script

frontend_tests/cypress/e2e/project/overview/canEditProjectTags.cy.js, recoco/apps/projects/static/projects/css/overview.scss, recoco/apps/projects/templates/projects/project/overview.html, recoco/apps/projects/templates/projects/project/tags.html, recoco/frontend/src/js/components/Tutorial.js
=> Possibilité d'ajouter et de modifier les tags d'un projet sur la présentation

recoco/apps/tasks/views/rest.py
Il s'agit de :
https://sentry.incubateur.net/organizations/betagouv/issues/144252/?referrer=alert_email&alert_type=email&alert_timestamp=1737466826525&alert_rule_id=153&notification_uuid=7f556eea-26fb-46c3-9f7d-12451a20da28&environment=production
=> [fix] Sentry issue 144252

recoco/apps/hitcount/tests/test_views.py, recoco/apps/hitcount/utils.py, recoco/apps/hitcount/views.py
Il s'agit de :
On n'enregistre pas de "hit" quand on est en mode détournement.
=> [fix] Do not register any hit when the current user is hijacked

recoco/apps/tasks/templates/tasks/tasks/task_update.html, recoco/frontend/src/js/components/ActionPusher.js
Il s'agit de :
Bug concernant le fait de pousser une reco en draft
=> [hotfix] publication reco draft

recoco/apps/home/admin.py, recoco/apps/home/signals.py, recoco/apps/invites/tests.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/475
=> [feat] Ajout du lien site sur User.profile au moment du login sur un nouveau portail

recoco/apps/projects/templates/projects/project/list-kanban.html, recoco/apps/projects/views/__init__.py, recoco/apps/projects/views/rest.py, recoco/frontend/src/js/components/KanbanProjects.js, recoco/frontend/src/js/utils/api.js, recoco/rest_api/urls.py
=> [feat] Dashboard improvements (subranch)

recoco/apps/projects/templates/projects/project/administration_panel.html
Il s'agit de :
- DSFRisation des button 
- Ajout de tootlip pour une meilleure compréhension 
Resolve #893
=> [feat] Ajout de tooltip sur les actions de la page paramètres d'un projet

recoco/apps/resources/static/resources/resources.scss, recoco/apps/resources/templates/resources/resource/fragments/resource_content.html
Il s'agit de :
Corrige l'affichage des liens contenus dans des balises <li> à l'intérieur d'une ressource.
=> [fix] update links display inside a resource

recoco/apps/geomatics/rest.py, recoco/apps/projects/context_processors.py, recoco/apps/projects/serializers.py, recoco/apps/projects/views/__init__.py, recoco/apps/projects/views/rest.py, recoco/apps/resources/rest.py
Il s'agit de :
- get rid of extra queries on departments in the project kanban page
- add missing prefetch statements in API addressbook
- add missing prefetch statements in API resources
- disable some context prodessor queries for admin / API
=> [chore] Some improvements

recoco/apps/projects/templates/projects/project/detail-ro.html, recoco/apps/projects/views/sharing.py
=> [fix] Correction de la vue partage d'état des lieux

recoco/apps/projects/templates/projects/project/fragments/action_pusher/resource_search.html, recoco/frontend/src/js/components/ActionPusher.js
=> [refactor] Affichage du label du champ de recherche d'une ressource externe

recoco/templates/default_site/header/menu-top-secondary.html
=> [feat] Suppression du badge des notif dans le header

frontend_tests/cypress/e2e/project/switchtender/assigned/canSeeAndUpdateAdvisorNote.cy.js, frontend_tests/cypress/e2e/project/switchtender/readOnly/canReadOnlyOverviewPage.cy.js, recoco/apps/projects/templates/projects/project/fragments/advisor_note.html, recoco/apps/projects/templates/projects/project/fragments/information_card.html
=> [feat] changement de wording sur la note interne

recoco/apps/crm/templates/crm/organization_list.html, recoco/apps/crm/views.py, recoco/apps/tasks/views/tasks.py
=> [chore] Optimisation des pages CRM

recoco/apps/social_account/adapters.py, recoco/settings/common.py, recoco/settings/development.py.example
Il s'agit de :
Faire fonctionner Proconnect
=> [fix] Proconnect

recoco/apps/social_account/adapters.py, recoco/settings/common.py
=> [fix] Proconnect URL and scopes

recoco/apps/projects/tests/test_projects.py, recoco/apps/survey/templates/survey/widgets/qs_summary_card.html
=> Correction d'un crash de page sur l'état des lieux en cas de section de question vide

recoco/apps/social_account/adapters.py, recoco/apps/social_account/provider.py, recoco/settings/common.py
Il s'agit de :
Fix bug allauth, on passait mal les scopes, et donc on ne récupérait pas correctement les infos user.
=> [fix] Proconnect user infos

recoco/templates/default_site/base.html
=> Ne pas afficher le footer pour les usagers connectés

recoco/apps/projects/templates/projects/project/fragments/action_pusher/resource_search.html
=> [refactor] Correction du wording sur le pousse reco (ressource externe)

recoco/apps/addressbook/serializers.py
Il s'agit de :
Workaround pour fixer https://sentry.incubateur.net/organizations/betagouv/issues/149134/?project=178&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
=> fix sentry issue on hyperlink fields

recoco/apps/addressbook/serializers.py
=> Fix API issue raised in sentry

recoco/apps/geomatics/rest.py
=> [fix] API communes N+1 

recoco/apps/tasks/models.py
Il s'agit de :
Réduction du nombre de requêtes en db sur la page des préfléchages
=> [chore] Réduction du nombre de requêtes en db sur la page des préfléchages

recoco/apps/projects/templates/projects/project/fragments/action_list_item.html
=> [feat] Lors du click d'une ressource pré-suggérée redirection vers le pousse-reco

recoco/apps/projects/templates/projects/project/fragments/geolocation/location_knowledge_footer.html
Il s'agit de :
Correction de l'affichage de l'edl dans de rare cas où l'affichage ne se fait que sur une colonne (un tiers de l'écran) comme l'exemple ci-dessous : 
Inversement d'une balise fermante div et d'une balise fermante endif.
=> [fix] Correction d'un bug d'affichage de l'edl 

recoco/apps/projects/templates/projects/project/overview.html, recoco/frontend/src/js/apps/projectDetails.js, recoco/frontend/vite.config.js
=> [fix] manifest vite

frontend_tests/cypress/support/views/project.js, recoco/apps/projects/templates/projects/project/fragments/email_reminder/learn_more_reminder.html, recoco/apps/projects/templates/projects/project/fragments/email_reminder/project_email_reminder.html
=> [Fix] Bannière de rappel d'email

recoco/apps/tasks/forms.py
Il s'agit de :
[Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/144857/?project=178)
=> [fix] Sentry 144857

recoco/apps/tasks/forms.py
Il s'agit de :
[Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/144876)
=> [fix] N+1 projects action

recoco/apps/crm/views.py
Il s'agit de :
[Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/)
=> [fix] N+1 crm user

recoco/apps/addressbook/admin.py
=> [fix] Addressbook admin

frontend_tests/README.md
=> [doc] Mise à jour en fonction des tags de fonctionnalité pour les tests frontend

recoco/apps/addressbook/views.py, recoco/apps/crm/models.py, recoco/apps/crm/views.py, recoco/apps/onboarding/forms.py, recoco/apps/onboarding/views.py, recoco/apps/projects/views/detail.py, recoco/apps/projects/views/documents.py, recoco/apps/resources/models.py, recoco/apps/survey/views/fill.py
Il s'agit de :
Mise à jour des imports de `reverse`.
=> [chore] Imports of the "reverse" method

recoco/apps/addressbook/serializers.py, recoco/apps/survey/tests/test_rest.py, recoco/apps/survey/views/rest.py, recoco/rest_api/urls.py
Il s'agit de :
- ajout d'un endpoint d'API pour retourner les questions disponibles pour un site
- optim sur l'api des answers
=> [feat] API qui retourne les questions pour un site

recoco/apps/crm/admin.py
=> add admin for crm Note with CSV export

frontend_tests/cypress.config.js, frontend_tests/cypress/e2e/project/staff/crm/canToggleProjectImpactTagInCRM.cy.js, frontend_tests/cypress/e2e/project/staff/kanban/canSearchAndDisplayProject.cy.js, frontend_tests/cypress/e2e/project/switchtender/otherTerritory/canReadOnlyOverviewPage.cy.js, frontend_tests/cypress/e2e/project/switchtender/readOnly/canReadOnlyOverviewPage.cy.js, frontend_tests/cypress/e2e/project/switchtender/readOnly/canReadOnlyPublicNotes.cy.js, frontend_tests/cypress/e2e/project/tasks/canSeeInlineTasks.cy.js, frontend_tests/cypress/e2e/project/tasks/canUnpublishTask.cy.js, frontend_tests/cypress/fixtures/projects/invites.json, frontend_tests/cypress/fixtures/projects/projects.json, frontend_tests/cypress/fixtures/projects/projectsMembers.json, frontend_tests/cypress/fixtures/projects/projectsSites.json, recoco/apps/projects/templates/projects/project/list-kanban.html, recoco/settings/frontend_tests.py
=> [test] mise à jour des test front end 

recoco/apps/crm/templates/crm/fragments/sidebar.html, recoco/apps/crm/templates/crm/note.html, recoco/apps/crm/templates/crm/organization_details.html, recoco/apps/crm/templates/crm/project_details.html, recoco/apps/crm/templates/crm/user_details.html, recoco/apps/crm/templates/crm/user_item.html, recoco/apps/crm/templatetags/crm_tags.py, recoco/apps/crm/tests/test_crm_tags.py, recoco/apps/crm/views.py
=> [feat] Ajout du user concerné par la note

recoco/apps/home/static/home/css/home/home.scss
Il s'agit de :
Modification du style du fichier home.scss pour adapter le styler des portails avec le nouveau héro.
Cette PR est liée avec celle de multisite : 
[https://github.com/betagouv/recoco-portails/pull/125](https://github.com/betagouv/recoco-portails/pull/125)
=> Modification du style du nouveau hero

recoco/apps/home/static/home/css/home/home.scss
Il s'agit de :
Création de classe avec la méthode bem pour rendre le nouveau héro responsive.
Cette PR est liée avec celle du multisite : https://github.com/betagouv/recoco-portails/pull/136
=> Fix responsive pour le nouveau héro des portails

frontend_tests/cypress/e2e/tools/tutorial/externalResourceTutorial.cy.js, frontend_tests/cypress/fixtures/settings/challengeDefinition.json, recoco/apps/projects/templates/projects/project/fragments/action_pusher/resource_search.html, recoco/apps/projects/templates/projects/project/navigation.html, recoco/apps/tasks/templates/tasks/tasks/task_create.html, recoco/apps/tasks/templates/tasks/tasks/task_update.html, recoco/frontend/src/css/buttons.css, recoco/frontend/src/js/config/tutorials.json, recoco/templates/default_site/tutorial/tutorial_hint.html
Il s'agit de :
Ajout d'un tutoriel s'affichant par défaut s'il n'a pas été validé au moins uen fois par l'utilisateur.rice.
Il se situe juste en dessous de la barre d'url de la resssource externe et donc uniquement pour l'import de cette dernière.
Resolve #1099
=> Tutoriel - Ajout d'un tutoriel pour l'importation des ressources externes

recoco/apps/addressbook/models.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1116
[Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/155996/?project=178&referrer=github_integration)
=> [fix] Sentry issue 155996

recoco/apps/home/templates/home/home.html, recoco/templates/default_site/base.html
Il s'agit de :
connectée [à cette PR coté multisite ](https://github.com/betagouv/recoco-portails/pull/126)
Resolve #1039
=> :cyclone: [feat] Affiche le footer sur la home même si l'on est connecté

recoco/apps/projects/serializers.py, recoco/apps/projects/tests/test_rest.py, recoco/apps/webhook/tests/test_signals.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1144
=> [feat] Synchro Grist - faire remonter les coordonnées GPS des projets

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/apps/home/static/home/css/home/home.scss, recoco/templates/default_site/footer.html
Il s'agit de :
Ajout de classes spécifiques et communes aux différents portails.
Suppression de code mort (commenté).
Cette PR est liée avec celle de multisite : https://github.com/betagouv/recoco-portails/pull/137
=> Feat/ Mise à jour du style des portails

recoco/apps/projects/templates/projects/project/fragments/tasks_modal/task_modal.html, recoco/apps/tasks/serializers.py, recoco/frontend/src/js/components/PreviewModal.js, recoco/frontend/src/js/components/Tutorial.js, recoco/frontend/src/js/store/previewModal.js
=> Correction d’une régression empêchant les recos avec ressource de s’afficher

recoco/apps/crm/templates/crm/siteconfiguration_tags_modal.html, recoco/apps/crm/templates/crm/siteconfiguration_tags_table.html, recoco/apps/crm/tests/test_crm_tags.py, recoco/apps/crm/views.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1142
=> [feat] CRM indiquer le nombre de projets impactés par la modification/suppression d'un tag

recoco/apps/demarches_simplifiees/models.py, recoco/apps/demarches_simplifiees/services.py, recoco/apps/demarches_simplifiees/tests/test_services.py, recoco/apps/demarches_simplifiees/utils.py, recoco/apps/geomatics/models.py
Il s'agit de :
- on peut retourner une valeur brute, no correspondant pas à une donnée en db
- on peut retourner uniquement le commentaire d'une réponse à l'EDL
- on peut retourner le couple code postal / code insee pour le mapping de la commune
- ajout de quelques champs supplémentaires sur le projet
=> [feat] Amélioration sur mapping DS

recoco/static/css/header/menu-burger.scss, recoco/templates/default_site/header/menu-top-secondary-right.html
Il s'agit de :
Modification du style des élements du header venant du cms wagtail pour uniformiser le style du header sur mobile.
=> Coorectif du responsive du header des éléments du cms

recoco/apps/tasks/tests/test_tasks.py, recoco/apps/tasks/views/tasks.py
=> [projects] Nouvelle statégie de placement des recos en fonction du temps passé depuis la dernière

recoco/apps/projects/models.py, recoco/apps/projects/templates/projects/project/administration_panel.html, recoco/apps/projects/tests/test_models.py, recoco/apps/projects/views/administration.py
Il s'agit de :
Prefetch du statut du projets pour éviter des N+1
=> [chore] Amélioration des perfs sur la page administration d'un projet

recoco/apps/projects/templates/projects/project/fragments/tasks_inline/task_item.html
=> [fix] UI DS integration

recoco/apps/tasks/serializers.py, recoco/apps/tasks/tests/test_rest_task_followup.py, recoco/apps/tasks/views/rest.py
Il s'agit de :
API patch task followup: le contact peut désormais être modifié
=> [fix] API Update followup contact

recoco/apps/communication/digests.py, recoco/apps/communication/tests/test_digests.py, recoco/apps/reminders/api.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1094
=> [feat] Modification des destinataires des mails B et C

recoco/apps/survey/admin.py
=> [feat] Améliorations de la page admin des réponses EDL

recoco/apps/crm/templates/crm/user_details.html, recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/apps/projects/templates/projects/project/fragments/owner/owner-details.html, recoco/apps/projects/templates/projects/project/fragments/user_invited.html, recoco/frontend/vite.config.js, recoco/templates/default_site/tools/contacts/contact_card.html
Il s'agit de :
Ajout du bouton permettant de copier l'email en réutilisant la méthode "clipboardCopy()" du composant Alpine User.
Resolve #1020
=> Feat/ Généralisation du bouton copier l'email

recoco/apps/projects/templates/projects/project/fragments/action_list_item.html
Il s'agit de :
Mise à jour du lien vers le "pousse-reco" pour sélection automatique du projet lorsqu'on arrive du pré-fléchage.
Resolve #1155 
=> [fix] Bug de sélection du projet lors du pré-fléchage

recoco/apps/projects/templates/projects/project/actions.html, recoco/apps/projects/templates/projects/project/administration_panel.html, recoco/apps/projects/templates/projects/project/fragments/administration/quit_project.html, recoco/apps/projects/templates/projects/project/fragments/email_reminder/project_email_reminder.html, recoco/apps/projects/templates/projects/project/fragments/owner/owner-details.html, recoco/apps/projects/templates/projects/project/fragments/survey_grid.html, recoco/apps/projects/templates/projects/project/navigation.html, recoco/apps/projects/templatetags/projects_extra.py, recoco/apps/projects/tests/test_templatetags.py, recoco/apps/projects/tests/test_utils.py, recoco/apps/projects/utils.py, recoco/apps/projects/views/detail.py, recoco/templates/default_site/user/user_card.html
Il s'agit de :
suppression de requêtes N+1 pour obtenir le contexte conseiller (`is_observer`, `is_advisor`)
=> [chore] Améliorations des perf sur les pages projet

recoco/apps/addressbook/rest.py, recoco/apps/addressbook/tests/test_rest_contact.py, recoco/rest_api/filters.py
Il s'agit de :
Recherche basé sur `TrigramWordSimilarity`
https://github.com/betagouv/recommandations-collaboratives/issues/1204
=> [feat] Amélioration de la recherche des contacts

recoco/apps/survey/static/survey/css/survey.scss
=> [fix][style] Padding block EDL

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss
Il s'agit de :
Correction de l'affichage du bouton fermer pour les fenêtres de tutoriels.
Au survol du bouton "X" la souris devenait un sens interdit alors que l'action du clique est possible.
Maintenant la souris devient une main pour indiquer que le clique est possible.
=> [fix] correction du curseur sur le hover du bouton fermer le tutoriel

recoco/apps/projects/templates/projects/project/internal_followup.html
Il s'agit de :
Remplacement du texte du bouton de l'éditeur dans l'espace conseiller de "Envoyer" par "Enregistrer".
=> [feat] changement du texte du bouton de l'espace conseiller

recoco/apps/projects/templates/projects/project/fragments/action_pusher/details_form.html, recoco/templates/default_site/tools/editor.html
Il s'agit de :
Amélioration du composant `editor` en y ajoutant la possibilité de surcharger le champ `file`
=> [feat] Ajout de la surchage pour le champ file de l'editor

recoco/apps/projects/templates/projects/project/fragments/owner/invite-not-accepted-banner.html
Il s'agit de :
Modification des conditions pour afficher la bannière.
=> [fix] Correction bug de non fonctionnement de la bannière référant n'a pas rejoint le projet

recoco/apps/survey/templates/survey/question_details.html
Il s'agit de :
Ajout de la mention obligatoire d'un commentaire dans l'état des lieux s'il est obligatoire.
Resolve #1212
=> [feat] ajout de la mention obligatoire d'un commentaire dans l'état des lieux

recoco/apps/projects/templates/projects/project/fragments/action_pusher/details_form.html
=> [hotfix] update reco form

frontend_tests/README.md, frontend_tests/cypress/e2e/project/overview/canMarkDiagnosticAsDoneAsStaff.cy.js, recoco/frontend/src/js/apps/conversationsNew.js, recoco/frontend/src/js/main.js
Il s'agit de :
Modification des imports dupliqués de HTMX. 
Resolve #1251
=> [fix] Correction du bouton Marquer le diag comme fait

recoco/apps/projects/forms.py, recoco/apps/projects/templates/projects/project/tags.html
=> [wording] page d'édition des tags

recoco/apps/projects/serializers.py
=> [fix] Region fields in api projects payload

recoco/templates/default_site/tools/organization_search.html
=> [fix] Mise à jour de la ref organization dans le template

recoco/apps/crm/templates/crm/projects_low_reach.html
=> [fix] Ajout de l'app CRM dans projet à faible répondant 

recoco/frontend/src/js/components/FeatureAddContact/CreateOrganizationModal.js, recoco/frontend/src/js/components/MultiSelect.js, recoco/templates/default_site/tools/contacts/multi_select.html
Il s'agit de :
Correction de la taille du sélecteur de départements lors de la création d'une demande de compte conseiller.
Réparation du sélecteur de départements lors de la création d'une organisation.
=> Correction multi-select pour la modération et la fonctionnalité contact

recoco/apps/projects/static/projects/css/push.scss, recoco/apps/projects/templates/projects/project/conversations_new.html, recoco/static/css/tools/editor.scss, recoco/templates/default_site/tools/editor.html
=> [feat] Possibilité d'ajout de nouvelle reco dans le nouvelle conv

recoco/apps/projects/models.py
Il s'agit de :
Cette permission manquante provoque une nouvelle migration après un makemigrations.
=> [fix] Missing permissions

recoco/templates/default_site/tools/contacts/create_organization_modal.html
=> [hotfix] create orga form

recoco/frontend/src/js/components/User.js, recoco/templates/default_site/tools/contacts/contact_card.html
Il s'agit de :
Ajout d'une div entourant l'intégralité de la carte contact pour initialiser le composant JS permettant le copier coller de mail dans tous les scénarios. Que le contact envoyé à la carte vienne de django ou du js.
Initialisation d'un contact dans le composant JS ci-dessus pour supprimer une erreur de contact non défini.
=> [fix] Réparation du bouton copier coller un mail

recoco/apps/metrics/sql_queries/hits.py, recoco/settings/common.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1255
=> [feat] Metrics hits

recoco/apps/crm/templates/crm/projects_low_reach.html, recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss
Il s'agit de :
L'en-tête des projets à faible impact dans le crm est maintenant fixe pour apparaître tout le temps.
resolve #1214
=> [style] en-tête crm projet à faible impact fixe

recoco/apps/projects/templates/projects/project/list-kanban.html, recoco/frontend/src/js/components/KanbanProjects.js
=> Correction du drag & drop sur le kanban

pyproject.toml, recoco/settings/common.py, recoco/template_loaders.py, requirements.txt, uv.lock
Il s'agit de :
Migration vers multisite2, backport du template loader dans le but de migrer à django5+
=> Migration vers django-multisite2

recoco/frontend/src/js/components/KanbanProjects.js
Il s'agit de :
Correction d'un autre cas à l'initialisation du kanban.
=> [fix] Kanban drag and drop 

recoco/apps/addressbook/rest.py
Il s'agit de :
- On trie les résultats de l'API de contacts par nom de l'organisation en premier
- Ajout d'un prefetch manquant
=> [fix] API contacts orderby

recoco/apps/survey/templates/survey/question_details.html
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1147
Il faudra créer un flag waffle `FLAG_EDIT_EDL`, fermé par défaut, sauf aux personnes de l'équipe recoco.
=> [feat] Flag edit EDL

recoco/apps/onboarding/forms.py, recoco/apps/onboarding/templates/onboarding/fragments/form-user.html, recoco/apps/onboarding/templates/onboarding/onboarding-signup.html, recoco/apps/onboarding/templates/onboarding/prefill-user.html, recoco/apps/onboarding/utils.py, recoco/apps/onboarding/views.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1070
=> [feat] Onboarding: personnalisation du message d'invitation

recoco/apps/projects/templates/projects/projects_moderation.html, recoco/frontend/src/js/components/User.js
Il s'agit de :
Correction d'un bug d'affichage de la carte contact.
Résolution d'une erreur de varibale non définie lors de l'appel du composant de la carte contact dans la modération.
=> Réparation du composant de la carte de contact

recoco/apps/home/forms.py, recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/static/css/account/login.scss, recoco/templates/default_site/account/login.html
Il s'agit de :
Refonte graphique de la page de connexion.
! Attention la nouvelle refonte indique que pour créer un compte (si l'utilisateur n'en a pas déjà un), il faut d'abord créer un projet. Il s'agit donc du nouvel ordre de l'onboarding des utilisateurs. 
PR a passé en même temps que celle relative à l'ordre de l'onboarding !
Resolve #1085
=> Refonte graphique de la page de connexion 

recoco/templates/default_site/account/email/email_confirmation_signup_message.html, recoco/templates/default_site/account/email/password_reset_key_message.html, recoco/templates/default_site/magicauth/email.html
Il s'agit de :
Refonte des mails de connexion, inscription et mot de passe oublié.
Cette PR est liée avec [cette PR sur multisites](https://github.com/betagouv/recoco-portails/pull/156).
resolve #1075 
- [] Aucun texte ne fait référence à du vocabulaire spécifique d'un métier
=> Refonte des mails de connexion, inscription et mot de passe oublié

recoco/templates/default_site/account/login.html
Il s'agit de :
Suppression d'une classe limitant la largeur de la page connexion.
Changement du texte pour le personne n'ayant pas de compte pour changer le wording projet par l'inscription actuelle.
=> Adaptation de la largeur de la page login + changement texte projet 

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss
Il s'agit de :
Ajout d'une classe pour une nouvelle bannière (bleu) dans le nouveau hero des portails.
Cette PR est liée [avec cette PR.](https://github.com/betagouv/recoco-portails/pull/157)
Resolve #1315
=> Ajout de classes pour le hero des portails

recoco/apps/survey/templates/survey/question_details.html
=> [fix] espace en trop dans le champ texte de l'EDL

recoco/templates/default_site/account/email/email_confirmation_signup_message.html, recoco/templates/default_site/account/email/password_reset_key_message.html, recoco/templates/default_site/magicauth/email.html
Il s'agit de :
Changement des variables des mails du serveur.
Changement d'un texte pour le mail de changement de mot de passe.
=> Changement variables et textes des emails du serveur

recoco/apps/onboarding/templates/onboarding/prefill-user.html, recoco/apps/projects/templates/projects/project/conversations.html, recoco/apps/projects/templates/projects/project/fragments/personal_dashboard/personal_dashboard_project_list.html, recoco/apps/projects/templates/projects/project/fragments/private_conversation.html, recoco/apps/projects/templates/projects/project/fragments/task/task_comment.html, recoco/apps/projects/templates/projects/project/fragments/tasks_inline/task_item.html, recoco/apps/projects/templates/projects/project/fragments/tasks_modal/task_modal.html, recoco/apps/projects/templates/projects/project/navigation.html, recoco/apps/projects/templates/projects/projects_moderation.html, recoco/templates/default_site/header/menu-top-secondary.html, recoco/templates/default_site/tools/contacts/search_contact_modal.html, recoco/templates/default_site/tools/editor.html
Il s'agit de :
Réparation de l'erreur sentry sur la variable "isOpenDeleteContact" qui n'est pas définie.
Réparation de l'erreur sentry sur le menu déroulant de sélection de rôle qui donnait une erreur _menu.classList is not defined au clique sur la croix pour ferme le menu.
Changement de wording des 3 dernières occurrences du bouton créer par déposer (un projet).
=> Réparation des erreurs sentry

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/static/css/tools/contact/create-contact-modal.scss, recoco/static/css/tools/contact/create-organization-modal.scss, recoco/static/css/tools/contact/multi-select.scss, recoco/templates/default_site/tools/contacts/create_contact_modal.html, recoco/templates/default_site/tools/contacts/create_organization_modal.html, recoco/templates/default_site/tools/contacts/multi_select.html
Il s'agit de :
Amélioration de la fonctionnalité des contacts en fonction des retours utilisateurs.rices : 
- Correction orthographique
- légère refonte de l'interface de la modale de création d'organisation
- responsive des modales de la fonctionnalité
Resolve #1326
Resolve #1323
=> Application des retours sur la fonctionnalité des contacts

recoco/apps/addressbook/serializers.py, recoco/apps/webhook/tests/test_signals.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1341
=> [feat] Update payload API contact (organisation group)

recoco/apps/tasks/serializers.py, recoco/apps/webhook/signals.py
Il s'agit de :
Ajout des recommandations dans les webhook
=> [feat] Webhook - recommandations

recoco/apps/addressbook/apps.py, recoco/apps/addressbook/models.py, recoco/apps/addressbook/signals.py, recoco/apps/addressbook/tests/test_signals.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1259
=> [feat] Création d'un groupe national au moment de la création d'une organisation

recoco/apps/addressbook/migrations/0013_alter_organization_name.py
=> [fix] Migration dedup organizations

recoco/apps/addressbook/migrations/0013_alter_organization_name.py
=> [fix] migration dedup

recoco/apps/resources/serializers.py, recoco/apps/tasks/serializers.py, recoco/apps/webhook/tests/test_signals.py, recoco/settings/common.py
=> [fix] Webhook recommendations

recoco/apps/addressbook/rest.py, recoco/rest_api/filters.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1324
=> [fix] Improve contact search

recoco/apps/metrics/sql_queries/projects.py
Il s'agit de :
https://github.com/betagouv/recommandations-collaboratives/issues/1361
=> [feat] Metrics commune latitude / longitude

recoco/apps/projects/templates/projects/project/list-kanban.html
=> [feat] Glisser déposer un projet à la fin d'une colonne dans le kanban

recoco/apps/resources/rest.py, recoco/apps/resources/serializers.py, recoco/apps/resources/tests/test_rest.py
Il s'agit de :
Modif du serializer et ajout de filtre (recommendation_id & nature)
=> [feat] Resource addon API changes

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/apps/resources/templates/resources/resource/fragments/resource_content.html
Il s'agit de :
Réparation du style d'un lien dans un bouton :
=> [fix] Modification style lien dans bouton

recoco/apps/addressbook/templates/addressbook/contact_list.html, recoco/frontend/src/js/components/FeatureAddContact/CreateOrganizationModal.js, recoco/templates/default_site/tools/contacts/create_contact_modal.html, recoco/templates/default_site/tools/contacts/create_organization_modal.html, recoco/templates/default_site/tools/contacts/search_contact_modal.html
Il s'agit de :
Revue et refactorisation du code.
=> [fix] Création et mise à jour d'une organisation 

frontend_tests/README.md, frontend_tests/cypress/e2e/auth/advisorSignup.cy.js, recoco/apps/home/forms.py, recoco/apps/home/templates/home/regional_actors.html, recoco/apps/home/tests/test_views_advisor_access.py, recoco/templates/default_site/account/fragments/departements_select_form.html, recoco/templates/default_site/account/fragments/pending_advisor_request_redirect.html
=> [feat] Demande de compte conseiller - le champ commentaire est obligatoire

recoco/apps/projects/templates/projects/project/fragments/project_banner/join_project_banner.html, recoco/frontend/src/js/utils/ajv/schema/ajv.schema.PrefillSetuserForm.js
=> Résolution des erreurs JS Sentry

frontend_tests/cypress/e2e/header/canAccessAdressBook.cy.js, frontend_tests/cypress/e2e/project/switchtender/assigned/canAccessAndUsePrivateNotes.cy.js, frontend_tests/cypress/e2e/project/tasks/canPublishDraftTask.cy.js, frontend_tests/cypress/e2e/project/tasks/contact/canCreateContactOrgaAndGroup.cy.js, frontend_tests/cypress/e2e/project/tasks/previewModal/canPostAFollowup.cy.js, frontend_tests/cypress/e2e/tools/task/canAddAfileInTask.cy.js, frontend_tests/cypress/support/commands.js, recoco/templates/default_site/header/menu-top-user-tools.html
Il s'agit de :
Réparation de 16 tests front end-to-end et mise en commentaire du 1ème test cassé en attendant le passage en production de la PR de résolution de cette dernière.
=> Réparation des tests front

recoco/apps/home/templates/home/privacy.html, recoco/templates/default_site/footer/footer.html
Il s'agit de :
Correction de l'affichage du lien sécurité dans le footer.
Resolve #1364
=> Modification affichage footer

recoco/templates/default_site/header/menu-top-user-tools.html
=> Correction d'un caractère oublié dans le menu (carnet de contacts)

recoco/frontend/src/js/apps/user.js, recoco/frontend/src/js/utils/stringToColor.js, recoco/templates/default_site/user/user_card.html
=> Correction erreur Sentry stringToColor

recoco/apps/onboarding/templates/onboarding/onboarding-summary.html, recoco/apps/projects/templates/projects/project/fragments/project_owner.html, recoco/apps/projects/templates/projects/project/navigation.html, recoco/apps/projects/templates/projects/project/overview.html, recoco/apps/projects/templates/projects/projects_moderation.html, recoco/apps/resources/templates/resources/resource/fragments/project_used.html, recoco/frontend/src/js/store/projectQueue.js, recoco/templates/default_site/header/menu-top-secondary.html
=> [fix] Ajout du nom de l'organisation du projet dans le menu d'accès rapide

recoco/apps/invites/templates/invites/invite_details.html, recoco/frontend/src/js/apps/pageInvitation.js, recoco/frontend/vite.config.js
=> hotfix(invites-page): Modification du chargement de la feuille de style + MAJ manifest

recoco/apps/projects/templates/projects/project/list-kanban.html
Il s'agit de :
(Ré)ajout des boutons déposer un projet et export CSV au tableau kanban des projets
=> [fix] Ajout de l'export dans le kanban des projets

recoco/apps/invites/tests.py, recoco/apps/invites/views.py
Il s'agit de :
crée une exception dédiée pour rediriger vers le projet associé à l'invitation plutôt que de sortir un 404
closes #1549
=> Redirige les liens d'invitation vers le projet associé au lieu d'afficher un 404

recoco/apps/addressbook/static/addressbook/css/contact_list.scss
Il s'agit de :
Ajustement de la taille de la barre de recherche pour permettre au filtre par département de s'afficher sur une seule ligne.
=> Réduction affichage de la barre de recherche du carnet d'adresse

recoco/apps/home/static/home/css/dsfr/custom-dsfr.scss, recoco/apps/projects/templates/projects/project/actions.html, recoco/apps/projects/templates/projects/project/administration_panel.html, recoco/apps/projects/templates/projects/project/conversations.html, recoco/apps/projects/templates/projects/project/documents.html, recoco/apps/projects/templates/projects/project/fragments/project_banner/banner_wrapper.html, recoco/apps/projects/templates/projects/project/fragments/project_banner/deleted_project_banner.html, recoco/apps/projects/templates/projects/project/internal_followup.html, recoco/apps/projects/templates/projects/project/knowledge.html, recoco/apps/projects/templates/projects/project/overview.html
Il s'agit de :
Ajout d'une bannière indiquant qu'un projet a été supprimé.
Blocage des cliques sur ces projets.
Resolve #1465
=> Ajout bannière projet supprimé
